### PR TITLE
Bug 1855291 - Handle FxA exceptions in getManageAccountURL

### PR DESCRIPTION
**Pull request by bendk**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1855291

### CODE REVIEW

**Comment by mhammond** [comment]
Is there a little more context available? I don't see the callers of this function and how they handle null, and in general it seems wrong that on exception callers now need to know to handle a null string when they will have no context about why it's null.

IOW, I'm wondering why the callers of this function don't handle the exception rather than handling the null value.

**Comment by bendk** [comment]
> IOW, I'm wondering why the callers of this function don't handle the exception rather than handling the null value.

That's a good question.  I mainly went this way because that's how the other [FirefoxAccount](https://github.com/mozilla-mobile/firefox-android/blob/ac8183515fbb299e46472aeeb44f0d7fba4a11b6/android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt) functions handle exceptions.

The only caller is the [AccountSettingsFragment](https://github.com/mozilla-mobile/firefox-android/blob/9dc2d889b41d76da463be92285d41b7ba866bab4/fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt#L382), so we could also easily make that catch the exception.

**Review by mhammond — APPROVED** [review]
As discussed with Ben, this doesn't seem ideal in terms of error handling, but will fix an issue on released versions. Hopefully we can fix this as we fix fxa errors in general.

**Comment by bendk** [comment]
@Mergifyio backport releases_v119

**Comment by DonalMe** [comment]
@mergify backport releases_v119

**Pull request merged**
