### PR TITLE
Bug 1878185 - Add ChangeDetectionMiddleware

### PR DESCRIPTION
**Pull request by MatthewTighe**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1878185

### CODE REVIEW

**Comment by jonalmeida** [comment]
Based on [the conversation in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1878185#c3), this is desired during testing. We have a `CaptureActionsMiddleware` already, so if we want, we can include behaviour there to observe a state there. What do you think about reusing that, or does it's current abilities work for your use case?

**Comment by MatthewTighe** [comment]
> Based on [the conversation in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1878185#c3), this is desired during testing. We have a `CaptureActionsMiddleware` already, so if we want, we can include behaviour there to observe a state there. What do you think about reusing that, or does it's current abilities work for your use case?

The `CaptureActionMiddleware` could be updated to include both, but I would prefer to keep them separate as they have different enough responsibilities. Additionally, `Capture` is in a test package, which is only included in the test [dependencies](https://searchfox.org/mozilla-mobile/source/firefox-android/fenix/app/build.gradle#713) for Fenix. We'd either need to move it, or import the dependency when we wanted to use it for debug logging.

TBH, when I demo'd the code in our show-n-tell it was also suggested that this would be a useful pattern to use more generally, for a few reasons:
1. Testing a middleware is easier than testing an observation in the `View`
2. Decouples business logic from Android framework components
3. Avoids difficulty with `Flow`s and keeps our async processing and queuing more encapsulated within the Store

Especially in light of our conversations the last few days, I don't want to rush this through without your approval given our intent to use it in more general cases eventually. Do you think it would make more sense to land this in Fenix for now, and consider upstreaming it with more robust documentation once it had had some time to soak?

**Comment by jonalmeida** [comment]
@MatthewTighe 

> We'd either need to move it, or import the dependency when we wanted to use it for debug logging.

Based on what I understood from your use case, this should be well annotated that is for testing purposes only. The reason I'm concerned about this landing without making that clear, is because this middleware overrides the whole purpose of observing the state if this middleware acts as a shortcut to observe fields changing within.

>   1. Testing a middleware is easier than testing an observation in the `View`

What does easier mean? What are we specifically trying to do in `onChange`? If by debug logging you mean something like `Log.d`, can't we just add that to the reducer when we want to do testing? Example:

```kotlin
internal object Reducer {
  fun reduce(state: State, action: Action): State {
    Log.d("$state $action")
    return when (action) {
      is Action.UpdateAction -> { }
    }
  }
}
```

>   3. Avoids difficulty with `Flow`s and keeps our async processing and queuing more encapsulated within the Store

If we're testing state changes with a middleware, we are creating a layer that is different from what the `View` is observing, and what we test using this middleware will not be the same from what the `View` receives. Another way of saying this is that we would get false-positive results from our debugging that would not have been caught because the developer didn't consider that observes are always async.

A weak reason I'd also add, because a developer shouldn't be doing this in a store but you can't prevent this: The middleware solution might not always give you the results you're looking for as well. If there are two middlewares making state changes based on different actions (which is what you shouldn't be doing), you would only be getting the last action that made the state change and not any previous action before that in the list.

**Comment by MatthewTighe** [comment]
Would still be happy to look into keeping this as a Fenix-only change until we have some live examples of whether it's useful, but wanted to respond to these points. 

> Based on what I understood from your use case, this should be well annotated that is for testing purposes only

It will not necessarily be only used for testing purposes. 

> What does easier mean? 

Observations of state typically happen within fragments or Composables, which require extensive test setup that run longer and more expensive tests (even just importing Robolectric will increase a standalone test runtime by about 20 seconds over JUnit IIRC). It introduces concurrency and lifecycle testing difficulties, but those are usually a well-understood  implementation pattern and don't need to be re-tested in every scenario. Generally, using fragments, activities, or Composables to handle business logic is less desirable than classes we have full control over and can execute without additional test runners.

> What are we specifically trying to do in onChange?

Whatever we want to, as is usually the case with middleware. They are the unrestricted, side-effectful portion of the architecture.

> If by debug logging you mean something like Log.d, can't we just add that to the reducer when we want to do testing?

This requires updating every action that can change the property you are interested in. Additionally, if we were ever interested in shipping something like opt-in debug telemetry to help handle incidences than the reducer would not be the appropriate place for side-effects.

> If we're testing state changes with a middleware, we are creating a layer that is different from what the View is observing, and what we test using this middleware will not be the same from what the View receives. Another way of saying this is that we would get false-positive results from our debugging that would not have been caught because the developer didn't consider that observes are always async.

This isn't intended to completely replace observations in the view, or tests for the view. The view should only need to observe state that is relevant to what it is displaying, though.

> A weak reason I'd also add, because a developer shouldn't be doing this in a store but you can't prevent this: The middleware solution might not always give you the results you're looking for as well. If there are two middlewares making state changes based on different actions (which is what you shouldn't be doing), you would only be getting the last action that made the state change and not any previous action before that in the list.

Middlewares don't directly make state changes, though they can dispatch additional actions to update that state. In that case, the callback would trigger for every action that completed the reducer chain. There are other edge cases where this wouldn't work perfectly, like if a middleware intercepts an action or rewrites an action. Both of those cases imply that a middleware has full knowledge of the system though, which may indicate a different problem anyway.

**Comment by jonalmeida** [comment]
Yeah, let's keep this in fenix only for now.

**Pull request closed without merging**
