### PR TITLE
Bug 1851974 - Add Oppo to the strict mode exclusion list

### PR DESCRIPTION
**Pull request by willdurand**
Feel free to close this PR if you think we shouldn't exclude a whole new
set of devices because the issue has only been reported on one device so
far. It's just annoying that our QA cannot use their usual test phone
with debug builds.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- ~~[ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one~~
- ~~[ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features~~

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1851974

### CODE REVIEW

**Comment by Amejia481** [comment]
Yeah, it's not great the we exclude all the those devices without having more data the issue is happening on more devices of the same brand, in my opinion we should wait until we have a clear signal or we may be silently missing issues.

**Comment by willdurand** [comment]
@jonalmeida @Amejia481 FWIW I agree but, at the same time, our QA is one more time unable to load a debug build to verify a patch that is time-sensitive...

**Comment by Amejia481** [comment]
I agree with @willdurand. As the exclusion is only been used on debug, given the priorities I think is OK to land this as it's and file a follow up to further investigate.

**Review by Amejia481 — APPROVED** [review]

**Review by jonalmeida — APPROVED** [review]
If this is blocking QA and it's time-sensitive, then I do not want to hold this up either. We can revisit it after.

**Comment by willdurand** [comment]
Thanks. As a follow-up, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1853187 but I am happy to discuss other ideas.

**Pull request merged**
