### PR TITLE
Bug 1820271 - Renew telemetry probes expiring in v114

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1820271

### CODE REVIEW

**Comment by rocketsroger** [comment]
# Request for data collection review form

All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data?
  * This data will help us understand how users are interacting with the recent synced tab card on the home page.
  * This data will provide statistics regarding the usage of the new start on home setting.
  * This data will provide statistics regarding the usage of the new recent tabs on the home screen.
  * This data will provide statistics regarding the usage of the new messaging framework.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? 
  * This data will help us understand how to better serve our sync user-base, as well as generally understand how active the feature is now.
  * This will give us an understanding of the usability of the new setting, info we will use for improving the user experience.
  * This will give us an understanding of how and if the user uses the new section.
  * This will help us understand usage patterns around messaging framework.

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
  * There are no other alternatives. 
4. Can current instrumentation answer these questions?
  * No. 
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki. 
Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.

Measurement Description | Data Collection Category | Tracking Bug #
-- | -- | --
Tabs Tray access point | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
Enter home screen | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
Open tabs tray on the home screen | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
Open Recent tab clicks | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
A message was shown | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
A message was dismissed | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
A message was clicked | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
A message was expired | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
A message was malformed | Category 2 - interaction data | https://bugzilla.mozilla.org/show_bug.cgi?id=1820271

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
  * https://dictionary.telemetry.mozilla.org/apps/fenix 
7. How long will this data be collected? Choose one of the following:
  * I want to permanently monitor this data. kbrosnan@mozilla.com will monitor this over time.

8. What populations will you measure?
  * All channels, all locales, all countries 
9. If this data collection is default on, what is the opt-out mechanism for users?
  * Default Glean SDK opt-out mechanism. 
10. Please provide a general description of how you will analyze this data.
  * Glean and Glam. 
11. Where do you intend to share the results of your analysis?
  * Only on Glean, Glam, and with mobile teams. 
12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
   * No third-party tools.

**Comment by rocketsroger** [comment]
# Request for Data Collection Renewal
### Renew for 1 year
Total: 10
———
`metrics.default_wallpaper`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/25539#issuecomment-1163393066

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - The team is still evaluating the performance of the wallpapers feature

———
`recent_tabs.show_all_clicked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/20138

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———
`wallpapers.wallpaper_settings_opened`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23382

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - The team is still evaluating the performance of the wallpapers feature

———
`recently_visited_homepage.history_highlight_opened`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23909

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - The team is still evaluating the performance of the wallpapers feature

———
`recently_visited_homepage.search_group_opened`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23909

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———
`recent_synced_tabs.recent_synced_tab_shown`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/24671

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———
`recent_synced_tabs.recent_synced_tab_time_to_load`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/24671

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———
`recent_synced_tabs.recent_synced_tab_opened`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/24671

2) When will this collection now expire?
    - TBD

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———
`recent_synced_tabs.show_all_synced_tabs_clicked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/24671

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———
`recent_synced_tabs.latest_synced_tab_is_stale`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/24671

2) When will this collection now expire?
    - 126

3) Why was the initial period of collection insufficient?
    - Homepage interaction that we would like to iterate on

———

**Comment by eliserichards** [comment]
> # Request for data collection review form
> 
> All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.
> 
>     1. What questions will you answer with this data?
> 
> 
>     * This data will help us understand how users are interacting with the recent synced tab card on the home page.
> 
>     * This data will provide statistics regarding the usage of the new start on home setting.
> 
>     * This data will provide statistics regarding the usage of the new recent tabs on the home screen.
> 
>     * This data will provide statistics regarding the usage of the new messaging framework.
> 
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
>     * This data will help us understand how to better serve our sync user-base, as well as generally understand how active the feature is now.
> 
>     * This will give us an understanding of the usability of the new setting, info we will use for improving the user experience.
> 
>     * This will give us an understanding of how and if the user uses the new section.
> 
>     * This will help us understand usage patterns around messaging framework.
> 
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
>     * There are no other alternatives.
> 
> 
>     4. Can current instrumentation answer these questions?
> 
> 
>     * No.
> 
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.    
>        Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Tabs Tray access point 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> Enter home screen 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> Open tabs tray on the home screen 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> Open Recent tab clicks 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> A message was shown 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> A message was dismissed 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> A message was clicked 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> A message was expired 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> A message was malformed 	Category 2 - interaction data 	https://bugzilla.mozilla.org/show_bug.cgi?id=1820271
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
>     * [https://dictionary.telemetry.mozilla.org/apps/fenix   ](https://dictionary.telemetry.mozilla.org/apps/fenix%E2%80%A8)
> 
> 
>     7. How long will this data be collected? Choose one of the following:
> 
> 
>     * I want to permanently monitor this data. [kbrosnan@mozilla.com](mailto:kbrosnan@mozilla.com) will monitor this over time.
> 
> 
>     8. What populations will you measure?
> 
> 
>     * All channels, all locales, all countries
> 
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
>     * Default Glean SDK opt-out mechanism.
> 
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
>     * Glean and Glam.
> 
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
>     * Only on Glean, Glam, and with mobile teams.
> 
> 
>     12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
>     * No third-party tools.

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

* Yes, through `metrics.yaml` and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

* Yes, through the "Send Usage Data" preference in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

* Yes, this data will be permanently collected. Kevin Brosnan (kbrosnan@mozilla.com) will be monitoring.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

* Category 2 - interaction data.

5) Is the data collection request for default-on or default-off?

* Default on.

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

* No. 

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**

* Yes.

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

* No.

## Result

data-review+

**Comment by eliserichards** [comment]
> # Request for Data Collection Renewal
> ### Renew for 1 year
> 
> Total: 10 ——— `metrics.default_wallpaper`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #25538 - New telemetry for what wallpaper is used fenix#25539 (comment)](https://github.com/mozilla-mobile/fenix/pull/25539#issuecomment-1163393066)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * The team is still evaluating the performance of the wallpapers feature
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.


> 
> ——— `recent_tabs.show_all_clicked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #19955: Add telemetry for home screen recent tabs. fenix#20138](https://github.com/mozilla-mobile/fenix/pull/20138)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 
> 


# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.


> ——— `wallpapers.wallpaper_settings_opened`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [closes #23381: add telemetry for wallpapers feature fenix#23382](https://github.com/mozilla-mobile/fenix/pull/23382)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * The team is still evaluating the performance of the wallpapers feature
> 


# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> 
> ——— `recently_visited_homepage.history_highlight_opened`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23821 - Add telemtry for RecentlyVisted Homepage fenix#23909](https://github.com/mozilla-mobile/fenix/pull/23909)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * The team is still evaluating the performance of the wallpapers feature
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> ——— `recently_visited_homepage.search_group_opened`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23821 - Add telemtry for RecentlyVisted Homepage fenix#23909](https://github.com/mozilla-mobile/fenix/pull/23909)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> ——— `recent_synced_tabs.recent_synced_tab_shown`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [for #24549: add telemetry for recent synced tab fenix#24671](https://github.com/mozilla-mobile/fenix/pull/24671)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 


# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> 
> ——— `recent_synced_tabs.recent_synced_tab_time_to_load`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [for #24549: add telemetry for recent synced tab fenix#24671](https://github.com/mozilla-mobile/fenix/pull/24671)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> ——— `recent_synced_tabs.recent_synced_tab_opened`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [for #24549: add telemetry for recent synced tab fenix#24671](https://github.com/mozilla-mobile/fenix/pull/24671)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> 
> ——— `recent_synced_tabs.show_all_synced_tabs_clicked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [for #24549: add telemetry for recent synced tab fenix#24671](https://github.com/mozilla-mobile/fenix/pull/24671)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

> ——— `recent_synced_tabs.latest_synced_tab_is_stale`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [for #24549: add telemetry for recent synced tab fenix#24671](https://github.com/mozilla-mobile/fenix/pull/24671)
> 
>     2. When will this collection now expire?
>        
>        * 126
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Homepage interaction that we would like to iterate on
> 
> 
> ———


# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

   * Yes.

2) Is the data collection covered by the existing Firefox Privacy Notice?

   * Yes.

# Result

data-review+

**Review by t-p-white — APPROVED** [review]
Code change lgtm 👍

**Pull request merged**
