### PR TITLE
Bug 1816184 - Add message for declarativeNetRequestFeedback permission

### PR DESCRIPTION
**Pull request by Rob--W**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1816184

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

**Comment by Rob--W** [comment]
Not really in a rush, but wondering what's next before merging this PR.

CI has some seemingly unrelated failures.

**Comment by Amejia481** [comment]
Sorry, I should tag for auto landing. 

It looks like there a is lint issue for `MaxLineLength`, I'll it and land the PR when everything is green, should we need to uplift this to v111?

```
[task 2023-02-13T15:47:14.206Z] 1134 kotlin files were analyzed.
[task 2023-02-13T15:47:14.505Z] /builds/worker/checkouts/vcs/android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt - 5min debt
[task 2023-02-13T15:47:14.506Z] 	MaxLineLength - [permissionToTranslation] at /builds/worker/checkouts/vcs/android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt:190:13
[task 2023-02-13T15:47:14.508Z] 
```

**Comment by Rob--W** [comment]
Uplifting is not needed. The feature is behind a pref.

**Comment by Amejia481** [comment]
Perfect, it should land as soon as everything gets ✅  !

**Comment by gabrielluong** [comment]
bors try

**Comment by JohanLorenzo** [comment]
> CI has some seemingly unrelated failures.

Sorry for this last minute regression. I fixed the issue with this backout https://github.com/mozilla-mobile/firefox-android/commit/6b1695f20432e6a7f84067f2c574e8e475d9b22d. The decision task is now back to green!

**Pull request merged**
