### PR TITLE
Bug 1818473  - Ignore case when searching through logins

### PR DESCRIPTION
**Pull request by gitstart**
The PR fixes issue of case sensitivity while searching through logins

### Issue video
[fnx-41-issue.webm](https://user-images.githubusercontent.com/35276272/220938020-e083e482-e732-4a99-98eb-86c2b9f13550.webm)

### Demo video after fix
[fnx-41-fix.webm](https://user-images.githubusercontent.com/35276272/220935027-fa5659cf-6d46-4d1f-a4a1-2b799453c8c8.webm)

### Pull Request checklist
- [x] **Quality:** This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests:** This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog:** This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility:** The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
 - Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
 - Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1818473

### CODE REVIEW

**Comment by Mugurell** [comment]
bors try

**Review by Mugurell — APPROVED** [review]
LGTM. Thank you for the quick patch!

**Comment by cpeterso** [comment]
@gitstart, thanks for all your great contributions! Do you have a Bugzilla account? If so, we can assign the Bugzilla bugs you've fixed to you so you get credit in Bugzilla for your work. :)

Like this PR's bug https://bugzilla.mozilla.org/show_bug.cgi?id=1818473

**Comment by Mugurell** [comment]
@Mergifyio backport releases_v111

**Pull request merged**
