### PR TITLE
Bug 1856496 - enable fx-suggest for nightly

### PR DESCRIPTION
**Pull request by tiftran**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1856496

### CODE REVIEW

**Comment by gabrielluong** [comment]
bors try

**Comment by linabutler** [comment]
Ooh, sorry, one more thing, @tiftran—could you please change [this line](https://github.com/mozilla-mobile/firefox-android/blob/4b8f76143317d2d172f5094c95dc53eea53c0681/fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L75) to `Config.channel.isNightlyOrDebug`? I forgot about that one!

**Comment by gabrielluong** [comment]
@tiftran Could you ask @mhammond or your manager to add you to https://github.com/orgs/mozilla-mobile/teams/ast or the appropriate team?

**Review by linabutler — CHANGES_REQUESTED** [review]
Thanks!

I forgot to mention one thing earlier—could you please change [this line](https://github.com/mozilla-mobile/firefox-android/blob/4b8f76143317d2d172f5094c95dc53eea53c0681/fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L75) to `Config.channel.isNightlyOrDebug`, too? Then we should be all set!

**Review by linabutler — APPROVED** [review]
Wonderful, thanks!

**Comment by gabrielluong** [comment]
bors try

**Pull request merged**
