### PR TITLE
Bug 1853416 - [ci] Add treescript action scope to version bump task

### PR DESCRIPTION
**Pull request by ahal**
Release Engineering is in the process of migrating automation that uses the `moz-releng-automation` bot accounts over to proper Github apps. Treescript (the code that handles version bumps) was updated to use the Github API rather than SSH keys associated with the bot accounts. Along the way, it broke backwards incompatibility by requiring the use of scopes.

This pull request makes the necessary changes to set scopes and continue using Treescript going forward. This PR needs to land at roughly the same time as https://github.com/mozilla-releng/scriptworker-scripts/pull/844 gets deployed to production.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1853416

### CODE REVIEW

**Comment by ahal** [comment]
This needs to land at around the same time as:
https://github.com/mozilla-releng/scriptworker-scripts/pull/844

**Review by JohanLorenzo — APPROVED** [review]
Looks good to me!

**Review by hneiva — APPROVED** [review]
LGTM, would this cause the Pull Request Labeler tests to fail?

**Comment by ahal** [comment]
> LGTM, would this cause the Pull Request Labeler tests to fail?

Shouldn't.. not sure what that's about

**Pull request merged**
