### PR TITLE
Bug 1825028 - Delay init of MozillaOnline build until privacy notice is accepted

### PR DESCRIPTION
**Pull request by csadilek**
See ticket for motivation.

We're essentially introducing a new activity for the `MozillaOnline` build so we can show our privacy notice prompt before initializing `FenixApplication` and `HomeActivity`, which in turn would otherwise initialize all our submodules e.g., Nimbus, Glean, Gecko. This change prevents unnecessary initialization.

Verify before landing:
- [x] MozillaOnline build uses new `MozillaOnlineHome` activity, all other builds do NOT.
- [x] Only MozillaOnline build shows privacy notice.
- [x] App initialization starts and completes only after user taps on "Agree and Continue", subsequent launches should not show the prompt. 
- [x] If the user taps on "Disagree and exit", Fenix exits and subsequent launches will continue to display the prompt.
- [x] No sub modules are initialized when notice is shown.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1825028

### CODE REVIEW

**Review by rxumoz — APPROVED** [review]
LGTM

**Review by csadilek — COMMENTED** [review]
I went through all the test case above and everything worked. Looks ready to land from my side.

**Review by jonalmeida — APPROVED** [review]
Likewise, tested this separate one more time for a sanity check. Let's land it then! 🙂

**Comment by csadilek** [comment]
@mergify backport releases_v112

**Pull request merged**
