### PR TITLE
Revert "Bug 1812843 - Increased the width for a CustomTabsToolbarFeature action button"

### PR DESCRIPTION
**Pull request by t-p-white**
Reverting mozilla-mobile/firefox-android#5141 as this patch has created more bugs, see: 

- https://bugzilla.mozilla.org/show_bug.cgi?id=1875933, 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1875788

https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843

### CODE REVIEW

**Review by MozillaNoah — APPROVED** [review]
big sad

**Comment by t-p-white** [comment]
@MozillaNoah, yep! Have reopened the OG bug.

**Comment by dsmithpadilla** [comment]
@t-p-white this wont land due to ci  failures in lint-ktlint-android-components

**Comment by t-p-white** [comment]
@dsmithpadilla thanks for the prompt. Strange as this was a revert commit, I wonder if these tests were 'ok' with the previous ktlint checks but not the current config. Have manually updated the affected lines (in`CustomTabsToolbarFeatureTest`)

**Comment by pascalchevrel** [comment]
@mergify backport releases_v123

**Pull request merged**
