### PR TITLE
Bug 1841095 - display customize homepage button even when shortcuts are disabled

### PR DESCRIPTION
**Pull request by VishnuSanal**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1841095

### CODE REVIEW

**Comment by rocketsroger** [comment]
Hi @VishnuSanal Sorry that I made a mess, I was trying to push into your change until I found out I don't have your repo permissions.  Your change have landed yesterday [here](https://github.com/mozilla-mobile/firefox-android/commit/8c620dfb93221b1d4ebe62d6a9881d9e6a0d477c).  Next time I'll just ask you to update the tests. 

Since your change has landed, I'll close this one.

**Comment by rocketsroger** [comment]
To clarify, Here's the [commit](https://github.com/mozilla-mobile/firefox-android/pull/4657/commits) with your change.  I did it with my PR since I messed up yours.

**Comment by rocketsroger** [comment]
But if you want to land it again with your PR, we could revert and try again.  Up to you.  Thanks

**Comment by VishnuSanal** [comment]
> But if you want to land it again with your PR, we could revert and try again.  Up to you.  Thanks

That's so nice of you! Need not, thanks. :) I'll pick a new issue :D

**Comment by rocketsroger** [comment]
> > But if you want to land it again with your PR, we could revert and try again.  Up to you.  Thanks
> 
> That's so nice of you! Need not, thanks. :) I'll pick a new issue :D

Thanks again for your contribution!  Please let me know which issue you want to work on and if there is anything I can help.

**Pull request closed without merging**
