### PR TITLE
Bug 1821261 – Enables unified search on nightly

### PR DESCRIPTION
**Pull request by mavduevskiy**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1821261

### CODE REVIEW

**Comment by gabrielluong** [comment]
@mavduevskiy Hi, you're probably running into UI tests failure here as a result of turning this on. This should be expected. I should look into disabling unified search for UI tests - See https://searchfox.org/mozilla-mobile/source/firefox-android/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt. Also, you will want to start having a conversation with the mobile testeng (eg @AaronMT) about UI test changes that will be needed when we ship this and get the appropriate bugs filed.

Lastly, I want to suggest a simplification to the changes you have here. I believe you could keep the Settings/Preferences for now and simply just make the changes to the FeatureFlag to enable this feature. I don't believe it's necessary to switch the checks from settings to the FeatureFlag. Rather we could just turn this feature on and later remove all these checks in one go when the feature is riding in release. It also appears to me that keeping the Settings will help you with the UI tests as well.

**Comment by rocketsroger** [comment]
> Also, you or the unified search team will want to start having a conversation with the #mobile-testeng (eg @AaronMT) about UI test changes that will be needed when we ship this and get the appropriate bugs filed.
> 

Good point, I'll take the point on this.  Thanks,

> Lastly, I want to suggest a simplification to the changes you have here. I believe you could keep the Settings/Preferences for now and simply just make the changes to the FeatureFlag to enable this feature.

I'm not sure about this.  If the user have switched (in Nightly) on and off Unified search feature before, then they will stay on the old implementation if we keep using the shared preference and only update the default value.

**Review by rocketsroger — CHANGES_REQUESTED** [review]
miss clicked to approve 😓

**Comment by mavduevskiy** [comment]
thanks, @gabrielluong @rocketsroger 
opened a [different pr](https://github.com/mozilla-mobile/firefox-android/pull/1192) to address both suggestions

**Pull request closed without merging**
