### PR TITLE
Bug 1816004 - Removed unused feature flags

### PR DESCRIPTION
**Pull request by milena-rosa**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1816004

### CODE REVIEW

**Comment by jonalmeida** [comment]
cc: @MatthewTighe @ohall-m for visibility in case either of you wanted to review this patch too that touches features you have both worked on.

Once the CI changes have been fixed, we'll land this patch. After the release cut probably.

**Review by ohall-m — COMMENTED** [review]
Thanks for removing these unused feature flags! r+ for Save to PDF

**Comment by MatthewTighe** [comment]
It looks like the linter is failing the CI checks. You can run that locally with `./gradlew ktlint`. 

I see that both `WallpaperUseCases` and `WallpaperSettingsFragment` now have unused imports. Without working through it myself, I suspect this will eventually lead to a situation where the `Legacy` wallpaper components are unused. This will also block the linter. 

If this is the case, we have two options:
1. Work through removing those components as part of this patch. I am happy to review that and help as needed.
2. Mark those components with `@Suppress("unused")` and file a follow-up to remove them.

Of the two, I would prefer the first option but am happy to help with the second as well.

**Comment by MatthewTighe** [comment]
👋 another update: for unrelated reasons I actually ended up needing to remove the unused wallpaper flag, which was blocking this PR. If you'd like to update the patch to only remove the save to PDF flag I think we would be happy to accept it 🙂

**Comment by gabrielluong** [comment]
@milena-rosa Thank you for the contribution, I have rebased the changes in https://github.com/mozilla-mobile/firefox-android/pull/2359 so that we can proceed with landing your work.

**Pull request closed without merging**
