### PR TITLE
Bug 1870335 - Merge content descriptions in the Add-ons details screen.

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1870335

### CODE REVIEW

**Comment by willdurand** [comment]
My understanding of the bug is that we should make each row in the "table" below the add-on's description announceable. While this PR updates the labels in the first column, it doesn't allow users with Talkback to navigate between each row more easily. I suppose something like this would be more like what Anna described:

```diff
diff --git a/fenix/app/src/main/res/layout/fragment_add_on_details.xml b/fenix/app/src/main/res/layout/fragment_add_on_details.xml
index 61bff2fcde..b0e34ba78b 100644
--- a/fenix/app/src/main/res/layout/fragment_add_on_details.xml
+++ b/fenix/app/src/main/res/layout/fragment_add_on_details.xml
@@ -28,6 +28,7 @@
             tools:text="@tools:sample/lorem/random" />
 
         <TextView
+            android:focusable="true"
             android:id="@+id/author_label"
             style="@style/AboutHeaderContentText"
             android:layout_width="wrap_content"
@@ -49,7 +50,6 @@
             app:layout_constraintEnd_toEndOf="parent"
             app:layout_constraintStart_toEndOf="@+id/author_label"
             app:layout_constraintTop_toBottomOf="@+id/details"
-            android:importantForAccessibility="no"
             tools:text="@tools:sample/full_names" />
 
         <View
```

Also, I don't think links should be marked as "no important for a11y".

Also, also, I think we should check with Anna what would work best here. E.g., should the entire row be a control? Some rows have "read-only" information but some others have a label and a link, and the "Homepage" only has a link. We should determine how we want users to navigate between each of these.

**Comment by willdurand** [comment]
> should the entire row be a control?

From: https://bugzilla.mozilla.org/show_bug.cgi?id=1870351

> If the recommendation in the [bug 1870335](https://bugzilla.mozilla.org/show_bug.cgi?id=1870335) would be implemented, then the entire row would be made a control, thus the touch targets would span the whole height of the row, and it would drastically improve the touch target experience.

So I guess, that's what we should aim for.

**Comment by Amejia481** [comment]
> My understanding of the bug is that we should make each row in the "table" below the add-on's description announceable. While this PR updates the labels in the first column, it doesn't allow users with Talkback to navigate between each row more easily

Could you help me to clarify here? I think the patch address navigation issue and announces each section as a row (Please ignore the rating section, it needs to be addressed 😅 ). 

**Without the fix**:

https://github.com/mozilla-mobile/firefox-android/assets/773158/bfe39480-f3d4-430e-9199-909653256a4b

**With the Fix**:

https://github.com/mozilla-mobile/firefox-android/assets/773158/b93aa5b7-b138-4aef-a19f-3ce3169ee0bf


> Also, I don't think links should be marked as "no important for a11y".

I'll address this!

**Comment by Amejia481** [comment]
With improvements:
(Navigating from down to up to better visualization as the add-on long description occupies a lot of the screen)

https://github.com/mozilla-mobile/firefox-android/assets/773158/5e80061d-dcd9-41b4-834b-95e001f4bc97

**Comment by willdurand** [comment]
@Amejia481 Thanks, in the emulator things worked differently for me. This looks better now (thanks!) but we should get someone from a11y to make sure we're fixing this part correctly. For instance, the control surface is still relatively small.

@anna-yeddi hello, could you help us here? thanks!

**Comment by anna-yeddi** [comment]
> @Amejia481 Thanks, in the emulator things worked differently for me. This looks better now (thanks!) but we should get someone from a11y to make sure we're fixing this part correctly. For instance, the control surface is still relatively small.
> 
> @anna-yeddi hello, could you help us here? thanks!

Apologies for the delay and thank you for the ping, @Amejia481 ! 

The patch is not exactly what I was expecting, but it does achieve the goals of reducing the number of swipes needed to navigate the page and of bundling the key-value pairs together. If the buttons are working when you double-tap them (I assume they do, but just to confirm), an R+ from me on the a11y side.

**Comment by Amejia481** [comment]
> If the buttons are working when you double-tap them (I assume they do, but just to confirm

Yes, they do :)

**Pull request merged**
