### PR TITLE
Bug 1820122 - Use b-android-xlarge to speed up external-gradle-dependencies jobs

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Let
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Looks like we have a permanent failure. Rebasing the code didn't change anything. @csadilek, who would be the right person to look into this test[1] to see if it happens to be hiding a race condition?

```
[task 2023-03-15T16:50:37.731Z] SUITE: org.mozilla.fenix.gleanplumb.state.MessagingMiddlewareTest
[...]
[task 2023-03-15T16:50:38.731Z]   TEST: WHEN restored THEN get messages from the storage
[task 2023-03-15T16:50:38.831Z]   FAILURE
[task 2023-03-15T16:50:38.931Z] 
[task 2023-03-15T16:50:38.932Z] java.lang.AssertionError: expected:<[Message(id=control-id, data=MessageData(#108), action=action, style=org.mozilla.fenix.nimbus.StyleData@1c9906a2, triggers=[triggers], metadata=Metadata(id=same-id, displayCount=0, pressed=false, dismissed=false, lastTimeShown=0, latestBootIdentifier=null))]> but was:<[]>
[task 2023-03-15T16:50:38.932Z] 	at org.junit.Assert.fail(Assert.java:89)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.Assert.failNotEquals(Assert.java:835)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.Assert.assertEquals(Assert.java:120)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.Assert.assertEquals(Assert.java:146)
[task 2023-03-15T16:50:38.932Z] 	at org.mozilla.fenix.gleanplumb.state.MessagingMiddlewareTest$WHEN restored THEN get messages from the storage$1.invokeSuspend(MessagingMiddlewareTest.kt:67)
[task 2023-03-15T16:50:38.932Z] 	at org.mozilla.fenix.gleanplumb.state.MessagingMiddlewareTest$WHEN restored THEN get messages from the storage$1.invoke(MessagingMiddlewareTest.kt)
[task 2023-03-15T16:50:38.932Z] 	at org.mozilla.fenix.gleanplumb.state.MessagingMiddlewareTest$WHEN restored THEN get messages from the storage$1.invoke(MessagingMiddlewareTest.kt)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invokeSuspend(TestBuilders.kt:212)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke(TestBuilders.kt)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke(TestBuilders.kt)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:211)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invokeSuspend(TestBuilders.kt:167)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(TestBuilders.kt)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(TestBuilders.kt)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersJvmKt$createTestResult$1.invokeSuspend(TestBuildersJvm.kt:13)
[task 2023-03-15T16:50:38.932Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
[task 2023-03-15T16:50:38.932Z] 	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at mozilla.components.support.test.rule.HelpersKt.runTestOnMain(Helpers.kt:56)
[task 2023-03-15T16:50:38.932Z] 	at mozilla.components.support.test.rule.HelpersKt.runTestOnMain$default(Helpers.kt:41)
[task 2023-03-15T16:50:38.932Z] 	at org.mozilla.fenix.gleanplumb.state.MessagingMiddlewareTest.WHEN restored THEN get messages from the storage(MessagingMiddlewareTest.kt:48)
[task 2023-03-15T16:50:38.932Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2023-03-15T16:50:38.932Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2023-03-15T16:50:38.932Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2023-03-15T16:50:38.932Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[task 2023-03-15T16:50:38.932Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
[task 2023-03-15T16:50:38.932Z] 	at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2023-03-15T16:50:38.932Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2023-03-15T16:50:38.932Z] 	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
[task 2023-03-15T16:50:38.932Z] 	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
[task 2023-03-15T16:50:38.932Z] 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
[task 2023-03-15T16:50:38.932Z] 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
https://firefox-ci-tc.services.mozilla.com/tasks/WXAPcqAnSxSk5GVwazLaZA/runs/5/logs/public/logs/live.log#L52184

**Comment by csadilek** [comment]
@JohanLorenzo I put up a PR which should fix this: https://github.com/mozilla-mobile/firefox-android/pull/1266

**Comment by rvandermeulen** [comment]
Looks like the Fenix gradle-dependencies job runs a bit faster than before with this change - 76min.

**Review by rvandermeulen — APPROVED** [review]
Thank you, this'll definitely help!

**Pull request merged**
