### PR TITLE
Bug 1858448 - Renew all telemetry to never expires

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1858448

### CODE REVIEW

**Comment by rocketsroger** [comment]
# Request for Data Collection Renewal
### Renew for never
Total: 7
———
`browser.locale_override`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———
`preferences.user_theme`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/5526

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———
`notifications.permission_granted`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/firefox-android/pull/475

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———
`metrics.search_widget_installed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/7474

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———
`search_widget.new_tab_button`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/7474

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———
`search_widget.voice_button`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/7474

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———
`search_widget.promote_dialog_shown`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/focus-android/pull/7657#issuecomment-1252242947

2) When will this collection now expire?
    - Never

3) Why was the initial period of collection insufficient?
    - Telemetry is now reviewed once a year

———

**Comment by rocketsroger** [comment]
> # Request for Data Collection Renewal
> ### Renew for never
> 
> Total: 7 ——— `browser.locale_override`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Issue #4901: Update metrics for data review on initial metrics focus-android#5065 (comment)](https://github.com/mozilla-mobile/focus-android/pull/5065#issuecomment-894328647)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ——— `preferences.user_theme`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5519: Add telemetry for theme settings. focus-android#5526](https://github.com/mozilla-mobile/focus-android/pull/5526)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ——— `notifications.permission_granted`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1803358 - Add telemetry to check if notifications are allowed for Focus #475](https://github.com/mozilla-mobile/firefox-android/pull/475)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ——— `metrics.search_widget_installed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #7249 Create a search widget focus-android#7474](https://github.com/mozilla-mobile/focus-android/pull/7474)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ——— `search_widget.new_tab_button`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #7249 Create a search widget focus-android#7474](https://github.com/mozilla-mobile/focus-android/pull/7474)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ——— `search_widget.voice_button`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #7249 Create a search widget focus-android#7474](https://github.com/mozilla-mobile/focus-android/pull/7474)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ——— `search_widget.promote_dialog_shown`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #7506 promote search widget dialog focus-android#7657 (comment)](https://github.com/mozilla-mobile/focus-android/pull/7657#issuecomment-1252242947)
> 
>     2. When will this collection now expire?
>        
>        * Never
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Telemetry is now reviewed once a year
> 
> 
> ———

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/apps/fenix )

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

android-probes@mozilla.com will be responsible for monitoring the data over time

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1 and 2, Technical and Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Comment by sarah541** [comment]
The proposal is great! Just a little confusion, why does the commit say renew **all** telemetry to never expires when we are only changing a couple?

**Comment by rocketsroger** [comment]
> The proposal is great! Just a little confusion, why does the commit say renew **all** telemetry to never expires when we are only changing a couple?

There are only 7 non-never telemetry in Focus.  So this change is only changing those 7 to never expires.

**Review by sarah541 — APPROVED** [review]

**Pull request merged**
