### PR TITLE
Bug 1854126 - App link does not redirect if no host or authority is present

### PR DESCRIPTION
**Pull request by hugomillwood**
Commit 9bae227 broke our apps' ability to login via Firefox with our SSO SDK AppAuth. This is mainly our fault since we did not list our redirect activity as exported. Previously though, `AppLinksUseCase` would have returned null for `resolveInfo` but would then also check if the scheme was supported by the engine or if there was a marketplace intent present, which in our case was false and we would fall through and be redirected.

I've now marked our redirect activity as exported, but we do not list any host or path in the intent filter and do not require anything else besides the scheme. I've removed the check for paths and authorities as I believe that a matching scheme should be enough if the package manager has found an activity that matches the URI.

Kind regards,

Hugo Millwood

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1854126

### CODE REVIEW

**Comment by hugomillwood** [comment]
@rocketsroger I would very much like to have my commit merged and receive the fair credit for my change instead of having a separate commit introduced.

**Comment by rocketsroger** [comment]
> @rocketsroger I would very much like to have my commit merged and receive the fair credit for my change instead of having a separate commit introduced.

Oh sorry, I did not see your commit here.  Let me see what I can do.  I can revert my change and land yours.  We arrived at the same solution but I wish I saw your change before I made mine.  Let me figure out how I can do this.  Thanks

**Comment by rocketsroger** [comment]
Hi @hugomillwood can you please update your change to this? It's a bit cleaner.  I'll then revert my change and land yours.

```                        
findActivities(appIntent).firstOrNull {
                            it.filter != null
                        }
```

**Comment by hugomillwood** [comment]
Hi @rocketsroger, thank you for taking the time to look through this, it's very appreciated :+1: 

I've updated my commit to use `firstOrNull` instead, I agree that it's cleaner.

**Comment by rocketsroger** [comment]
> Hi @rocketsroger, thank you for taking the time to look through this, it's very appreciated 👍
> 
> I've updated my commit to use `firstOrNull` instead, I agree that it's cleaner.

Great, on Monday I'll revert my change on Nightly and land yours.  Sorry for not noticing your PR earlier.  Thanks for your contribution!

**Review by rocketsroger — APPROVED** [review]

**Comment by Djfe** [comment]
interesting how the change broke more than just mailto: sms: geo: and tel: links 🤔
Great to also have a test-case so you prevent it from happening again 👍
Thanks for the fix and looking into it, both of you 😊

**Pull request merged**
