### PR TITLE
Bug 1831555 - Refactor false assertions  in UI tests

### PR DESCRIPTION
**Pull request by AndiAJ**
Bug 1831555 - Refactor false assertions in UI tests

Noticed that the false assertions take too much time, so I've tried to refactor them by decreasing the waiting times.

- For all the UI tests to complete it takes on average 7m - 9m minutes.
- With these changes the test running time decreases to approx. 6 minutes.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1831555

### CODE REVIEW

**Review by sv-ohorvath — COMMENTED** [review]
What if you replaced them with assertTrue(item.waitUntilGone(waitingTime))? This gives enough time for the object to disappear and also move on quickly if the object is not visible, instead of waiting for the given amount of time for it to exist.

**Comment by AndiAJ** [comment]
Thanks, not sure if this will make any difference, it still has to wait a certain amount of time.

**Comment by AndiAJ** [comment]
With the original implementation - 5m 59s matrix-1xmumxwx4m3m9 FINISHED
With waitUntilGone -  7m 25s matrix-roma2dageo9ra FINISHED

**Review by AaronMT — APPROVED** [review]
Looks OK to me, I'd wait if Oana has any followup

**Review by sv-ohorvath — APPROVED** [review]

**Pull request merged**
