### PR TITLE
Bug 1835453 - Handling content-type with extra information correctly

### PR DESCRIPTION
**Pull request by jackyzy823**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1835453

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]
Thanks for the patch @jackyzy823!

**Comment by jackyzy823** [comment]
@claudiu64 I think this is intentional.
See comment:
https://github.com/mozilla-mobile/firefox-android/blob/69b5255a5b51087f37b5af01df5c479d445c92d8/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L173

**Comment by claudiu64** [comment]
> @claudiu64Cred că acest lucru este intenționat. Vezi comentariul:
> 
> https://github.com/mozilla-mobile/firefox-android/blob/69b5255a5b51087f37b5af01df5c479d445c92d8/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L173

And can it be solved?

**Comment by claudiu64** [comment]
> @claudiu64 I think this is intentional. See comment:
> 
> https://github.com/mozilla-mobile/firefox-android/blob/69b5255a5b51087f37b5af01df5c479d445c92d8/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L173

@jackyzy823 And can it be solved?

**Comment by jackyzy823** [comment]
@claudiu64  Sorry, I think no.  As it claims that https://github.com/mozilla-mobile/firefox-android/blob/69b5255a5b51087f37b5af01df5c479d445c92d8/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L161-L163 , and it does exactly  the same thing as https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/webkit/URLUtil.java;l=305?q=android.webkit.URLUtil.guessFileName&sq=

**Comment by claudiu64** [comment]
> @claudiu64 Sorry, I think no. As it claims that
> 
> https://github.com/mozilla-mobile/firefox-android/blob/69b5255a5b51087f37b5af01df5c479d445c92d8/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L161-L163
> , and it does exactly the same thing as https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/webkit/URLUtil.java;l=305?q=android.webkit.URLUtil.guessFileName&sq=

@jackyzy823 Maybe you can do something to change this.

**Pull request merged**
