### PR TITLE
Bug 1873858 - Remove the deprecated service-telemetry

### PR DESCRIPTION
**Pull request by Dexterp37**
This remove the legacy telemetry system (service-telemetry) from Focus/Klar Android, see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1873858) for more details and the related proposal.

Most of this should be pretty straightforward (mostly deletions), some important highlights or things to watch out for:

- `isTelemetryEnabled` was moved and we probably want some QA to make sure everything still works.
- The legacy client id is no longer `set` on the relevant pings, because we don't have it anymore
- The activation ping was using the legacy client id as the 'activation id' (odd!), we're now generating a new UUID.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1873858

### CODE REVIEW

**Review by mcarare — APPROVED** [review]
LGTM!

**Review by travis79 — CHANGES_REQUESTED** [review]
delenda est service-telemetry ⚱️ 

This has been a long time coming, congratulations and 🎉 !

One minor question before I can approve this...   I don't see any "migration" code to remove the storages used by service-telemety, have you taken that into consideration?

**Comment by Dexterp37** [comment]
> One minor question before I can approve this... I don't see any "migration" code to remove the storages used by service-telemety, have you taken that into consideration?

That's a good question, thanks for bringing this up! Yes, I considered this but I don't think it's worth the engineering work to create something "purge" it. Given the average size of the Glean [storage database in Fenix (< 200kb)](https://sql.telemetry.mozilla.org/dashboard/fenix-errors), assuming the same conditions apply to Focus, I don't think it should be too much of a big deal?

**Comment by travis79** [comment]
> > One minor question before I can approve this... I don't see any "migration" code to remove the storages used by service-telemety, have you taken that into consideration?
> 
> That's a good question, thanks for bringing this up! Yes, I considered this but I don't think it's worth the engineering work to create something "purge" it. Given the average size of the Glean [storage database in Fenix (< 200kb)](https://sql.telemetry.mozilla.org/dashboard/fenix-errors), assuming the same conditions apply to Focus, I don't think it should be too much of a big deal?

Can we file a bug to produce a decision-brief to this effect? I'd like to be able to justify why the storage might still be around in a year when someone asks 🙏, or file a bug and we can get around to it eventually. My concern was that we considered this, not that we did anything specific about it.

**Review by travis79 — APPROVED** [review]
Changing my r- to an r+ based on the discussion in the PR

**Comment by Dexterp37** [comment]
> That's a good question, thanks for bringing this up! Yes, I considered this but I don't think it's worth the engineering work to create something "purge" it. Given the average size of the Glean [storage database in Fenix (< 200kb)](https://sql.telemetry.mozilla.org/dashboard/fenix-errors), assuming the same conditions apply to Focus, I don't think it should be too much of a big deal?

Captured the rationale here: https://bugzilla.mozilla.org/show_bug.cgi?id=1873935

**Pull request merged**
