### PR TITLE
Bug 1845357 - Remove the first run onboarding

### PR DESCRIPTION
**Pull request by gabrielluong**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1845357

### CODE REVIEW

**Comment by gabrielluong** [comment]
@AaronMT @sv-ohorvath Could I have one of you review the UI test changes? This is removing the first run onboarding, which is the long scroll onboarding with the individual cards on the Home screen. This is being replaced with the new Juno onboarding that is currently in production.

**Review by rocketsroger — APPROVED** [review]
Looks good to me.  I would suggest that we also remove `shouldShowJunoOnboarding` and the related Nimbus flag before doing this so user will now by default get the new onboarding experience.

**Review by sv-ohorvath — APPROVED** [review]

**Review by AndiAJ — APPROVED** [review]
👍🏽

**Review by AaronMT — APPROVED** [review]
Everything under `/androidTest/` LGTM, assuming, as mentioned on Slack that `skipOnboarding` isn't affected as it's used in setting up the test rules

**Comment by t-p-white** [comment]
Does [this doc](https://github.com/mozilla-mobile/firefox-android/blob/9b5e751d54df65bbcb6fc2650ba05dda6e3b7147/fenix/app/tags.yaml#L111C1-L114C21) need updating?

**Comment by gabrielluong** [comment]
> Does [this doc](https://github.com/mozilla-mobile/firefox-android/blob/9b5e751d54df65bbcb6fc2650ba05dda6e3b7147/fenix/app/tags.yaml#L111C1-L114C21) need updating?

That file is auto-generated and we didn't remove all of the onboarding metrics. https://github.com/mozilla-mobile/firefox-android/blob/9b5e751d54df65bbcb6fc2650ba05dda6e3b7147/fenix/app/tags.yaml#L6-L7

Safe to say no action necessary here.

**Comment by gabrielluong** [comment]
> Everything under `/androidTest/` LGTM, assuming, as mentioned on Slack that `skipOnboarding` isn't affected as it's used in setting up the test rules

This is still the case that `skipOnboarding` is utilized to skip the onboarding via https://searchfox.org/mozilla-mobile/source/firefox-android/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt#214

**Pull request merged**
