### PR TITLE
Removed code to report Sentry errors for Rust `log::error` calls

### PR DESCRIPTION
**Pull request by bendk**
The new system was merged in #12266 and we have started using it for all components in app-services.  I've been checking the Sentry reports and it seems like it's working, so let's remove the old one.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by bendk** [comment]
I didn't think this needed a CHANGELOG entry, but I could definitely write one if requested

**Comment by jonalmeida** [comment]
> I didn't think this needed a CHANGELOG entry, but I could definitely write one if requested

I think that's fine.

**Review by jonalmeida — APPROVED** [review]
Thanks for the cleanup PR!

**Comment by bendk** [comment]
Monday is great, thanks for the review.

**Comment by jonalmeida** [comment]
CI configs were changed so PRs needed to be rebased manually in order to be landed.

**Pull request merged**
