### PR TITLE
Bug 1860919 - Send Glean pings for Wikipedia Firefox Suggestion impressions and clicks.

### PR DESCRIPTION
**Pull request by linabutler**
This PR:

* Adds new facts, `wikipedia_suggestion_clicked` and `wikipedia_suggestion_impressed`, to the `feature-fxsuggest` component.
* Emits `fx-suggest` Glean pings for those facts in Fenix's `MetricController`.

This PR doesn't add any new probes, but expands the existing `fx_suggest` metrics added for AMP suggestions in https://bugzilla.mozilla.org/show_bug.cgi?id=1857092 and https://bugzilla.mozilla.org/show_bug.cgi?id=1858542 to also be emitted for Wikipedia suggestions. Would you still like a data review form, @HarrisonOg?

@ncloudioj I can't tag you for review—I think you might need to [join the `mozilla-mobile` GitHub organization first](https://bugzilla.mozilla.org/show_bug.cgi?id=1851706), and then I can add you to the `ast` team—but could you take a look also, please?

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1860919

### CODE REVIEW

**Comment by linabutler** [comment]
# Request for data collection review form

1) What questions will you answer with this data?

* Do users see Wikipedia suggestions when they interact with the awesomebar?
* Where in the awesomebar do users see Wikipedia suggestions?
* Do users click on Wikipedia suggestions after seeing them?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?

Product and business requirements, to validate the Enhanced Cross-Platform Suggest experiment. We'll also use this data to improve our suggestions for users on mobile.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

This data isn't currently collected on mobile, and there are no alternatives.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.

This PR does not add any new probes, but expands the `fx-suggest` ping metrics for impressions and clicks added in bug 1858542 and bug 1857092 to also cover Wikipedia suggestions. The following new values are sent for the existing `fx-suggest` ping metrics:

<table>
  <tr>
    <td>Measurement</td>
    <td>Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>`fx_suggest.advertiser`</td>
    <td>`"wikipedia"` for Wikipedia suggestions.</td>
    <td>2</td>
    <td>1860919</td>
  </tr>
  <tr>
    <td>`fx_suggest.context_id`</td>
    <td>The same contextual services user identifier that's used for Top Sites and sponsored suggestions.</td>
    <td>2</td>
    <td>1860919</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).

7) How long will this data be collected?  Choose one of the following:

This data will be collected permanently. The Suggest team (Lina Butler, Tif Tran, and Nan Jiang) will be responsible for the permanent collections.

8) What populations will you measure?

The Firefox Suggest experiment population; currently US-only.

9) If this data collection is default on, what is the opt-out mechanism for users?

These collections are Glean. The opt-out can be found in Settings.

10) Please provide a general description of how you will analyze this data.

We'll create Looker dashboards from this data, and analyze it with the existing tools that we use on the Suggest team for Desktop data.

11) Where do you intend to share the results of your analysis?

The results will be shared with the Suggest team.

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?

No.

**Comment by HarrisonOg** [comment]
> # Request for data collection review form
> 
>     1. What questions will you answer with this data?
> 
> 
>     * Do users see Wikipedia suggestions when they interact with the awesomebar?
> 
>     * Where in the awesomebar do users see Wikipedia suggestions?
> 
>     * Do users click on Wikipedia suggestions after seeing them?
> 
> 
>     2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
> Product and business requirements, to validate the Enhanced Cross-Platform Suggest experiment. We'll also use this data to improve our suggestions for users on mobile.
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> This data isn't currently collected on mobile, and there are no alternatives.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> No.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
> This PR does not add any new probes, but expands the `fx-suggest` ping metrics for impressions and clicks added in bug 1858542 and bug 1857092 to also cover Wikipedia suggestions. The following new values are sent for the existing `fx-suggest` ping metrics:
> Measurement 	Description 	Data Collection Category 	Tracking Bug #
> `fx_suggest.advertiser` 	`"wikipedia"` for Wikipedia suggestions. 	2 	1860919
> `fx_suggest.context_id` 	The same contextual services user identifier that's used for Top Sites and sponsored suggestions. 	2 	1860919
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).
> 
>     7. How long will this data be collected?  Choose one of the following:
> 
> 
> This data will be collected permanently. The Suggest team (Lina Butler, Tif Tran, and Nan Jiang) will be responsible for the permanent collections.
> 
>     8. What populations will you measure?
> 
> 
> The Firefox Suggest experiment population; currently US-only.
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> These collections are Glean. The opt-out can be found in Settings.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> We'll create Looker dashboards from this data, and analyze it with the existing tools that we use on the Suggest team for Desktop data.
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> The results will be shared with the Suggest team.
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?
> 
> 
> No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/apps/fenix )

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

android-probes@mozilla.com will be responsible for monitoring the data over time

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data.

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Review by HarrisonOg — APPROVED** [review]
looks good to me!

**Comment by linabutler** [comment]
@Mergifyio backport releases_v120

**Pull request merged**
