### PR TITLE
Bug 1837656 - Added the "Challenge the Default" drawable resources

### PR DESCRIPTION
**Pull request by t-p-white**
### Figma design

figma designs

### Light mode:

ctd light 1
ctd light 2
ctd light 3

### Night mode: 

ctd night 1
ctd night 2
ctd night 3

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1837656

### CODE REVIEW

**Comment by t-p-white** [comment]
ℹ️ All files auto generated. 
Images were exported as SVGs from Figma design and configured vector asset using Android Studio Asset Studio

**Comment by rahulsainani** [comment]
> ℹ️ All files auto generated - `tools:ignore="VectorRaster"` manually added Images were exported as SVGs from [Figma design](https://www.figma.com/file/veU5n91XZ3SBRP2Gp4Xdlu/EU_Challenge-the-default?type=design&node-id=474-12515&t=r7rYzApr2YJRnvdv-0) and configured vector asset using Android Studio Asset Studio

I'd advocate for keeping the warning (removing the suppression) so we remember and know there is an issue with larger paths in vectors, I understand this is urgent, so we don't have to ask for optimized resources now, but we can always do that after this has landed.

**Comment by rahulsainani** [comment]
Lint is failing with unused resources, you can add in the baseline or update lint.xml to ignore these 3 files. Why didn't lint fail for lifestyle images tho?

Also, we might need the keep rules similar to lifestyle images so R8 doesn't strip these images.

**Review by rahulsainani — APPROVED** [review]
Looks good! 👍 

I just realized there's english text in the default browser image, won't be ideal for non english locales 💭

**Comment by t-p-white** [comment]
https://github.com/Mergifyio backport releases_v115

**Pull request merged**
