### PR TITLE
Bug 1848297 - Use dialogs instead of snackbars for add-ons install errors

### PR DESCRIPTION
**Pull request by Amejia481**
…

image

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1848297

### CODE REVIEW

**Comment by willdurand** [comment]
I only looked at the screenshot above and I think this needs some tweaks to match the UX spec: https://bugzilla.mozilla.org/show_bug.cgi?id=1848297#c1

**Comment by Amejia481** [comment]
Thanks for reviewing!

> I only looked at the screenshot above and I think this needs some tweaks to match the UX spec: https://bugzilla.mozilla.org/show_bug.cgi?id=1848297#c1

Sure, I can update it, which parts are you referring specifically? 

The title format (**{Extension}  installation failed**), which includes the name of the extension could make the title **long and less meaningful**, also in most of the cases of our existing strings already include the extension, this **could sound a bit redundant**, as we will have that name in both places title and body, some examples: 


image
image

**Comment by Amejia481** [comment]
I opted for having a generic title without the name on it, which doesn't include the name of the extension  **"Failed to install"**, Wdyt?

**Comment by Amejia481** [comment]
Closed in favour of https://github.com/mozilla-mobile/firefox-android/pull/3332

**Pull request closed without merging**
