### PR TITLE
Bug 1799666 - Import focus-android configuration in .mergify.yml

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Depends on https://github.com/mozilla-mobile/firefox-android/pull/281

⚠️ Do not land. This PR will be merged on Tuesday, December 13th 2022. This is part of the migration of focus to the monorepo.

### CODE REVIEW

**Review by gbrownmozilla — APPROVED** [review]
Mostly a rubberstamp here, but it looks reasonable.

**Comment by gabrielluong** [comment]
@JohanLorenzo This needs to be rebased with https://github.com/mozilla-mobile/firefox-android/pull/281

**Comment by JohanLorenzo** [comment]
> ideally this PR just have the commit with the mergify changes

You're 100% right! Done. This PR doesn't depend on #281 anymore.

**Comment by JohanLorenzo** [comment]
No need to wait for CI on this one. It's just some mergify changes.

**Pull request merged**
