### PR TITLE
[focus] Enable about:config for all release builds

### PR DESCRIPTION
**Pull request by DroidFreak32**
### Pull Request checklist

- [] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by Mugurell** [comment]
Currently `about:config` is not available in release by design.
Escalated the issue to re-evaluate.

**Comment by Mugurell** [comment]
Thank you for your interest in this!
Re-checked the current status and with `about:config` being a power user feature that at the moment would allow even breaking certain features of the app the decision is to not enable this in release.
For users interested in modifying the app behavior through `about:config` changes it's recommended to use the beta or nightly versions of the app.

**Comment by DroidFreak32** [comment]
Okay, I came from a perspective that if a user is advanced enough to know about:config then they already expect things to break if they are not careful , but I understand your reasoning.

I was only concerned with performance impact in beta v/s release versions due to additional debugging available in the beta.

**Comment by msbit** [comment]
@Mugurell is there an issue in bugzilla tracking allowing/not allowing `about:config` in release builds?

**Comment by lazymonkey2** [comment]
> It's working on version 124.1.0.

I've tried it but it doesn't remember the changes I've done (refresh the page and it returns to the default value).

**Comment by SwuduSusuwu** [comment]
> about:config is available in the release build of Firefox for Android (and Firefox Focus) through the following URL:
> 
> ```
> chrome://geckoview/content/config.xhtml
> ```
> 
> It's working on version 124.1.0. Thanks to Kaoxt of Mozilla Ideas for [sharing this info](https://connect.mozilla.org/t5/ideas/firefox-for-android-about-config/idc-p/53769/highlight/true#M31405).

With Firefox 124 this was a fix.
With Firefox 126, can not goto `chrome://geckoview/content/config.xhtml`, if you type this or copy&paste this just redirects to `https://www.google.com/search?q=geckoview%2Fcontent%2Fconfig.xhtml`
Now the fix is to uninstall **Firefox** and install **Firefox Focus**.from https://play.google.com/store/apps/details?id=org.mozilla.focus

**Comment by parcelcat** [comment]
@lazymonkey2 @SwuduSusuwu The URL workaround is still working for me in version 127. Firefox redirected me to a search engine on my first attempt, but when I tried again, it brought up the about:config editor. After that, entering the URL showed the about:config editor every time. My changes persist when I refresh and restart Firefox.

Making the about:config editor available at about:config instead of this workaround URL would still be an improvement, of course.

**Pull request closed without merging**
