### PR TITLE
Add AC version of NimbusBuilder to construct AC version of Nimbus object

### PR DESCRIPTION
**Pull request by jhugman**
Fixes [EXP-2893](https://mozilla-hub.atlassian.net/browse/EXP-2893).

This will not build until ~https://github.com/mozilla/application-services/pull/5239 lands and is released~ AC upgrades to App Services [v96.0.1][1].

[1]: https://github.com/mozilla/application-services/releases/tag/v96.0.1

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Review by boek — APPROVED** [review]
🚀

**Comment by jhugman** [comment]
This can only land once @MickeyMoz upgrades App Services to [96.0.1][1].

[1]: https://github.com/mozilla/application-services/releases/tag/v96.0.1

**Comment by bendk** [comment]
Is there automation for this?  I thought we had to manually update the version in the PR.  Checking in because I'd love to get the new app-services version merged to get some more context on our errors.

**Comment by jcristau** [comment]
> Is there automation for this? I thought we had to manually update the version in the PR. Checking in because I'd love to get the new app-services version merged to get some more context on our errors.

The automation doesn't bump major app-services version, but #199 pulls in 96.0.1.

**Pull request merged**
