### PR TITLE
Bug 1860587 - Set allow_checks_interruption to false

### PR DESCRIPTION
**Pull request by dsmithpadilla**
By setting allow_checks_interruption false, Mergify will not interrupt the checks. Instead, a pull request with a higher priority will be inserted just after the pull requests that currently have checks running.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1860587

### CODE REVIEW

**Review by jcristau — COMMENTED** [review]
Doesn't this kind of defeat the purpose of the "high priority" rule?

**Comment by dsmithpadilla** [comment]
@jcristau My understanding is that this only stops it from cutting the 1st in line that is being processed (when set to false). So in a queue of 10 it will be No. 2 but wont interrupt the 1st one that probably is already almost ready to be merged.

**Comment by jcristau** [comment]
> @jcristau My understanding is that this only stops it from cutting the 1st in line that is being processed (when set to false). So in a queue of 10 it will be No. 2 but wont interrupt the 1st one that probably is already almost ready to be merged.

Ah, I see, I guess that's because speculative_checks is 1 and so no checks are running for any other queued PRs?

**Comment by dsmithpadilla** [comment]
> > @jcristau My understanding is that this only stops it from cutting the 1st in line that is being processed (when set to false). So in a queue of 10 it will be No. 2 but wont interrupt the 1st one that probably is already almost ready to be merged.
> 
> Ah, I see, I guess that's because speculative_checks is 1 and so no checks are running for any other queued PRs?

Right. So the checks are only happening on the tip of the queue. The rest of the items in queue are simply in line. Setting this to false moves the urgent PR to the top of the line of those who have no checks currently running. Currently, it interrupts the tip.

**Review by jcristau — APPROVED** [review]

**Pull request merged**
