### PR TITLE
Bug 1812175 - Turn on Sync page and touch target suggestion is displayed.

### PR DESCRIPTION
**Pull request by gitstart**
### What
The PR makes the `Turn on Sync page` touch target area larger

### Steps to test
1. Have the Accessibility scanner installed and opened.
2. Go to the main menu and tap on "Sign in to sync" option
3. Scan the page

### Screenshots
| Issue | Fix |
| ----- | --- |
| issue | 69 fix |

### Pull Request checklist
 - [ ] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1812175

### CODE REVIEW

**Review by Mugurell — CHANGES_REQUESTED** [review]
Thank you for working on this!

Left a comment about how situations like this are currently handled in the app and what we should also do here.

In this patch I see one issue fixed but others remaining. Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1812175 the expectation are:
> No suggestions are made for the specific page.

Do you plan to address the rest of the issues on this screen also?

**Comment by gitstart** [comment]
Thank you @Mugurell for reviewing🙏.
Will soon push the requested changes. 🚀

**Comment by gitstart** [comment]
The remaining accessibility issue is a `Text scaling` issue on the toolbar which will require changing the toolbar UI for the whole app.

**Comment by gitstart** [comment]
Hello @Mugurell,
Requested Changes Pushed. 🚀
Thank you 🙏

**Comment by gabrielluong** [comment]
@MozillaNoah We briefly discussed accessibility issues with buttons. I was wondering what was our current take on addressing such issues? Should the XML buttons be made to align to the design component specs or just use increase tap area?

**Comment by MozillaNoah** [comment]
> @MozillaNoah We briefly discussed accessibility issues with buttons. I was wondering what was our current take on addressing such issues? Should the XML buttons be made to align to the design component specs or just use increase tap area?

I'd advocate for using `increaseTapArea` for now, as we continue to investigate the best approach for aligning all of our XML components in this XML-to-Compose interim state we're presently in (I'm not necessarily signing off on the increase of 16 though, as I have not vetted that number in this scenario). The XML buttons will be trickier as they live across multiple files and not all of them utilize the styles, so I think the accessibility issue doesn't have to be held up while we try to find a more silver bullet solution.

**Review by Mugurell — APPROVED** [review]
LGTM.
Thank you!

**Pull request merged**
