### PR TITLE
Bug 1818058 - Enable TCP by default for all releases

### PR DESCRIPTION
**Pull request by Mugurell**
TCP will still be controllable through Nimbus but by default it will be enabled now on all releases.
As a side effect this will also have the TCP being shown in the onboarding screen. See https://github.com/mozilla-mobile/firefox-android/pull/823.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1818058

### CODE REVIEW

**Comment by Amejia481** [comment]
Are we planning to uplift to v111?

**Review by Amejia481 — APPROVED** [review]
As long a we don't uplift to v111, before addressing [the timing issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1818056) between the cookie banner handling dialog and the TCP CFR. This looks good.

**Comment by Mugurell** [comment]
> Are we planning to uplift to v111?

I think not but a double check with @cpeterso would not hurt.

**Comment by Amejia481** [comment]
Thanks!

**Comment by cpeterso** [comment]
Just confirming what @Mugurell said:

We don't need to uplift this change to Beta 111. We don't want TCP enabled by default in 111 because that's that release were we want to gradually enable it using the Nimbus rollout. :chart_with_upwards_trend:

**Pull request merged**
