### PR TITLE
Bug 1805256 - Adding legacy telemetry id to Glean pings

### PR DESCRIPTION
**Pull request by travis79**
This adds the legacy client_id to Glean pings to aid in validation and verification between the two systems.

This requires data-review before landing, awaiting the review in Bug 1805256 from @eliserichards 

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by travis79** [comment]
@jonalmeida I've been asked if this can be considered for uplift in a dot release, or at a minimum into v109 (beta). Where should I go to request this?

**Comment by jonalmeida** [comment]
> @jonalmeida I've been asked if this can be considered for uplift in a dot release, or at a minimum into v109 (beta). Where should I go to request this?

I will reply back to you offline about the uplift process.

**Comment by travis79** [comment]
Data-review+ from @eliserichards in [Bug 1805256](https://bugzilla.mozilla.org/show_bug.cgi?id=1805256#c8)

**Comment by jonalmeida** [comment]
Thanks, let's land this now - it's a pretty safe change to land today.

> I will reply back to you offline about the uplift process.

We got approval for the uplift to 108. I'll notify relman about this change as we prepare the uplift.

**Comment by jonalmeida** [comment]
@mergifyio backport releases_v108

**Review by jonalmeida — APPROVED** [review]
Forgot to approve it here too after the repo migration. 😄

**Comment by jonalmeida** [comment]
@mergifyio refresh

**Pull request merged**
