### PR TITLE
Bug 1835525 - Bookmark saves to the last select folder

### PR DESCRIPTION
**Pull request by jackyzy823**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1835525

### CODE REVIEW

**Review by titooan — APPROVED** [review]
Hey @jackyzy823,
Thanks a lot for putting this PR! It looks great to me, I have nothing to complain about.

I tested the current behavior in Fenix and tested your patch, here are the videos of the results, showing the bug is fixed. In the fixed case, the folder shown in the Edit screen in consistent with the folder where the bookmark is really saved. 

| Current Behavior in Fenix  | Behavior fixed in this patch |
| ------------- | ------------- |
| <video src="https://github.com/mozilla-mobile/firefox-android/assets/460498/846a12d8-f710-4e01-ac14-f93101531fb1" /> | <video src="https://github.com/mozilla-mobile/firefox-android/assets/460498/0b4045f8-1649-4069-b312-482ac4e46052" /> | 

The UI tests also ran succesfully (see PR #4577), so we can land this.

Great job, and thanks again for this patch!

**Comment by DonalMe** [comment]
Lint failures https://firefoxci.taskcluster-artifacts.net/LwDXf4eERi-UQ2_UM8Elhw/1/public/reports/detekt/detekt.html

**Comment by DonalMe** [comment]
@jackyzy823 @titooan just in case you didn't spot the above message. The PR is in a needs landing state but the linter CI is failing.

**Comment by jackyzy823** [comment]
Hello, @DonalMe @titooan , i update the document , the only change in the push is from `@property` to `@param` in the document of `DefaultTabsTrayController`

**Pull request merged**
