### PR TITLE
Bug 1815628 - Refactored Navigation Graph to show `Saved Login Page` after new Credentials added. 

### PR DESCRIPTION
**Pull request by gitstart**
The PR fixes the issue where `saved Login Page` is shown after a new `login` is added

### Issue Screenshots
https://www.loom.com/share/3b5cc33e7a7a4ae79282531292666c52

### Fix Screenshots
[fnx-15-fix.webm](https://user-images.githubusercontent.com/93866435/214651093-fc6a787e-5456-4aa5-878c-1354a6820782.webm)

### Pull Request checklist
- [x] **Quality:** This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests:** This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog:** This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility:** The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
 - Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
 - Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

**GitHub Automation**
Fixes https://github.com/mozilla-mobile/fenix/issues/27855
https://bugzilla.mozilla.org/show_bug.cgi?id=1815628
https://bugzilla.mozilla.org/show_bug.cgi?id=1815628
https://bugzilla.mozilla.org/show_bug.cgi?id=1815628
https://bugzilla.mozilla.org/show_bug.cgi?id=1815628

### CODE REVIEW

**Review by Mugurell — COMMENTED** [review]
Thank you for your contribution!
This change will have to be validated by UX and product. Will keep you posted with the discussions result.

**Comment by gitstart** [comment]
Thank you @Mugurell for reviewing🙏.
Will soon push the requested changes. 🚀

**Comment by topotropic** [comment]
Thanks for the PR! This is looking good from a UX point of view.

**Comment by gitstart** [comment]
> Thanks for the PR! This is looking good from a UX point of view.

Acknowledged. 🎉

**Comment by Mugurell** [comment]
@gitstart I see some CI tasks failing, can you look into those issues?

Also it seems like this patch uses the same flow discussed [here](https://github.com/mozilla-mobile/firefox-android/pull/907#pullrequestreview-1306974017) which elides some performance improvements be have by creating a new`SavedLoginsFragment` and in that forcing a new query of the logins storage.

I am okay with landing both patches using this direction at the beginning of the next Nightly cycle (March 14) to allow us to try and refactor them later to avoid creating new fragments.

**Comment by gitstart** [comment]
Hello @Mugurell,
Requested changes pushed. 
Thank you!🙏

**Comment by amedyne** [comment]
@Mugurell Can you check if this is ready to be landed?

**Comment by Mugurell** [comment]
bors try

**Review by Mugurell — APPROVED** [review]
Previously there was a unit test failing, probably intermittent, all is green now.
We can improve the state handling later, opened https://bugzilla.mozilla.org/show_bug.cgi?id=1824379 for that.
Thank you @gitstart for helping with this, I'll help merge.

**Pull request merged**
