### PR TITLE
Bug 1812825 - Fix overlapping text in BrowserMenuImageTextCheckboxButton

### PR DESCRIPTION
**Pull request by sryze**
Constrain the start of the checkbox element to the end of button text and make it "ellipsizable" by setting width to 0dp, so that they don't overlap and the menu item expands together with the checkbox.

Fixes https://github.com/mozilla-mobile/fenix/issues/22509

Migrated from https://github.com/mozilla-mobile/android-components/pull/12949

Screenshot before:
before

Screenshot after:
after

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1812825

### CODE REVIEW

**Comment by gabrielluong** [comment]
Hello, we recently ran into a hiccup during the monorepo migration where our CI tasks weren't checking the right files and running the appropriate build and test runs for any of the changed files and components. Unfortunately, this means your PR will need to rebase in order for CI to run appropriately to ensure all the appropriate checks are passing prior to landing. Sorry for the inconvenience!

**Comment by sryze** [comment]
@gabrielluong OK, I've rebased the branch

**Comment by t-p-white** [comment]
@sryze thank you for your contribution, great work 👍  I have resolved the above conflicts.

**Review by t-p-white — APPROVED** [review]
🚢

**Pull request merged**
