### PR TITLE
Bug 1803141 - part 8: Build focus only when it or one of its dependen…

### PR DESCRIPTION
**Pull request by JohanLorenzo**
…cies change

Depends on https://github.com/mozilla-mobile/firefox-android/pull/282 and https://github.com/mozilla-mobile/firefox-android/pull/253

⚠️ Do not land. This PR will be merged on Tuesday, December 13th 2022. This is part of the migration of focus to the monorepo.

### CODE REVIEW

**Review by gbrownmozilla — APPROVED** [review]

**Comment by JohanLorenzo** [comment]
We're behind schedule on today's migration. This PR doesn't test anything past what the decision task executes. The task is green so I'm manually merging it as it.

**Comment by JohanLorenzo** [comment]
@mergifyio releases_v109

**Comment by JohanLorenzo** [comment]
@Mergifyio backport releases_v109

**Comment by JohanLorenzo** [comment]
@Mergifyio backport releases_v108

**Pull request merged**
