### PR TITLE
Upgrade Application Services to v96.0.1

### PR DESCRIPTION
**Pull request by jhugman**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/fenix/pull/27899#issuecomment-1320501801

**Comment by Amejia481** [comment]
bors try

**Comment by Amejia481** [comment]
Release diff https://github.com/mozilla/application-services/compare/v95.0.1...v96.0.1

**Comment by Amejia481** [comment]
bors try

**Comment by Amejia481** [comment]
bors try

**Comment by Amejia481** [comment]
It looks like we have some, [network](https://github.com/mozilla-mobile/firefox-android/pull/199/checks?check_run_id=9622463153) issues but the `try` tests passed.  
image


```
[vcs 2022-11-21T17:46:15.338Z] successfully cleaned git checkout!
[vcs 2022-11-21T17:46:15.341Z] TinderboxPrint:<a href='https://github.com/mozilla-mobile/firefox-android/commit/eea949bac430a192401474bcc211c8890fcc09ca' title='Built from firefox-android commit eea949bac430a192401474bcc211c8890fcc09ca'>eea949bac430a192401474bcc211c8890fcc09ca</a>
[task 2022-11-21T17:46:15.341Z] executing ['bash', '-cx', '/builds/worker/checkouts/vcs/taskcluster/scripts/are_dependencies_completed.py E8ZJn8XOTha5v8qZFa_DQg cqRu3P-6QjilTJvoTkPjNw']
[task 2022-11-21T17:46:15.343Z] + /builds/worker/checkouts/vcs/taskcluster/scripts/are_dependencies_completed.py E8ZJn8XOTha5v8qZFa_DQg cqRu3P-6QjilTJvoTkPjNw
[task 2022-11-21T17:46:15.686Z] Fetching status of 2 dependencies...
[task 2022-11-21T17:46:15.686Z] Statuses fetched.
[task 2022-11-21T17:46:15.687Z] Traceback (most recent call last):
[task 2022-11-21T17:46:15.687Z]   File "/builds/worker/checkouts/vcs/taskcluster/scripts/are_dependencies_completed.py", line 52, in <module>
[task 2022-11-21T17:46:15.687Z]     main()
[task 2022-11-21T17:46:15.687Z]   File "/builds/worker/checkouts/vcs/taskcluster/scripts/are_dependencies_completed.py", line 46, in main
[task 2022-11-21T17:46:15.687Z]     check_all_dependencies_are_completed(result.dependencies_task_ids)
[task 2022-11-21T17:46:15.687Z]   File "/builds/worker/checkouts/vcs/taskcluster/scripts/are_dependencies_completed.py", line 32, in check_all_dependencies_are_completed
[task 2022-11-21T17:46:15.687Z]     raise ValueError(f'Some tasks are not completed: {non_completed_tasks}')
[task 2022-11-21T17:46:15.687Z] ValueError: Some tasks are not completed: {'E8ZJn8XOTha5v8qZFa_DQg': 'failed'}
[taskcluster 2022-11-21 17:46:16.164Z] === Task Finished ===
[taskcluster 2022-11-21 17:46:16.165Z] Unsuccessful task run with exit code: 1 completed in 19.006 seconds
```

**Review by Amejia481 — APPROVED** [review]

**Comment by jhugman** [comment]
Breaking changes in Fenix fixed by https://github.com/mozilla-mobile/fenix/pull/27899
Breaking changes in Focus-Android fixed by https://github.com/mozilla-mobile/focus-android/pull/8012

**Pull request merged**
