### PR TITLE
Bug 1799622 - A password deleted in the password manager, is still visible in the list afterwards

### PR DESCRIPTION
**Pull request by gitstart**
The PR fixes saved Logins not updating immediately a login is deleted

### Fix description
Navigate back to the saved login screen, rather than just popping back stack 

### Issue video
[fnx-58-issue.webm](https://user-images.githubusercontent.com/93866435/216845977-f84bf078-76b6-4fc9-a02b-10649605c509.webm)

### Demo video after fix
[fnx-58-fix.webm](https://user-images.githubusercontent.com/93866435/216846010-0f993584-f300-40cc-a9ff-acc418ce14b7.webm)

### Pull Request checklist
- [x] **Quality:** This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests:** This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog:** This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility:** The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
 - Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
 - Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1799622

### CODE REVIEW

**Review by Mugurell — CHANGES_REQUESTED** [review]
Thank you for your contribution!

The issue may be seen as a regression after [these changes](https://searchfox.org/mozilla-mobile/rev/7193103ed8eeee2e9d1e0527d15e9a0a20f5c762/firefox-android/fenix/app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt#226-234) which will specifically avoid refreshing logins.

The current proposal is to create and navigate to a new `SavedLoginsFragment` which will create a new `ViewModel` [here](https://searchfox.org/mozilla-mobile/rev/7193103ed8eeee2e9d1e0527d15e9a0a20f5c762/firefox-android/fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt#72) and in this allow to bypass the above discussed check.
This works but as seen [here](https://github.com/mozilla-mobile/firefox-android/pull/907/files#diff-d3a0a7d86e8b528c358d419a5c64ce24ff4522904bb92b9fc9ac1390d1afeb69R67-R68) it does introduce a high level of complexity and will also skip the performance improvements done before - avoiding to query the entire list of logins.

For the scenario of editing/deleting logins I propose
- using the [Fragment Result API](https://developer.android.com/guide/fragments/communicate#fragment-result) with the `EditLoginFragment` sending back to `SavedLoginsFragment` through a new payload the updated details or if a certain login was deleted or
- sharing the `LoginsFragmentStore` between `EditLoginFragment, `LoginDetailFragment` and `SavedLoginsFragment` through a ViewModel scoped to a subgraph of those fragments so that the they can update the same data that the `SavedLoginsFragment` would display. As an added benefit this would ensure we only query the logins list only one time between all the fragments in the subgraph and improving the performance.

**Comment by gitstart** [comment]
Thank you @Mugurell for reviewing🙏.
Will soon push the requested changes. 🚀

**Comment by gitstart** [comment]
Hello @Mugurell,
Requested changes are pushed. 🚀

**Comment by Mugurell** [comment]
> Hello @Mugurell, Requested changes are pushed. 🚀

Looks to me like the current patch has still the initial approach in which we navigate to another instance of `SavedLoginsFragment` which circumvents a specific performance improvement we have currently as discussed here - https://github.com/mozilla-mobile/firefox-android/pull/907#pullrequestreview-1306974017 ?

**Comment by gitstart** [comment]
> > Hello @Mugurell, Requested changes are pushed. 🚀
> 
> Looks to me like the current patch has still the initial approach in which we navigate to another instance of `SavedLoginsFragment` which circumvents a specific performance improvement we have currently as discussed here - [#907 (review)](https://github.com/mozilla-mobile/firefox-android/pull/907#pullrequestreview-1306974017) ?

Hello @Mugurell,
Pushed requested changes with improvisation.  
Thank you!

**Review by Mugurell — APPROVED** [review]
Thank you!
Tested this on top of https://github.com/mozilla-mobile/firefox-android/pull/916 and everything works good.
Later improvements can be made in https://bugzilla.mozilla.org/show_bug.cgi?id=1824379.

**Comment by Mugurell** [comment]
bors try

**Pull request merged**
