### PR TITLE
Bug 1807126 - Increased gap between slider and scale value

### PR DESCRIPTION
**Pull request by gitstart**
### What
The dot from the scale overlaps the percentage number on Accessibility screen

### Fix description
Increased seekBar end margin from 60 to 70.

### Steps to test

1. From the device's settings, change the font size to the biggest option (extra large/huge).
2. Tap on 3 dot menu.
3. Open Settings.
4. Go to Accessibility and change the scale to a maximum (200%).
5. Observe the page.

### Screenshots
Issue video:
https://www.loom.com/share/23e1da8882fd48179c16b6a5ee2c353f

Fix video:
https://www.loom.com/share/59a4cf570c09455b845f74f290bc4b64

### Pull Request checklist
 - [x] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1807126

### CODE REVIEW

**Review by titooan — CHANGES_REQUESTED** [review]
Thanks for your contribution! 
I tested on a Pixel 7, and if the issue is not totally fixed with the highest scale value on this phone. 
I propose then to use `80dp`, that fixes the issue and also has the advantage of beeing a multiple of 8 (and thus be closer to the design recommandations).

We will be able to land it right after you update your patch.

**Comment by gitstart** [comment]
Hi @titooan , requested changes has been pushed, can you please review?

**Comment by titooan** [comment]
bors try

**Review by titooan — APPROVED** [review]
Looks good to me, thanks a lot for your contribution!

**Pull request merged**
