### PR TITLE
Bug 1813753 - Skip the half-expanded state when collapsing the Tabs Tray

### PR DESCRIPTION
**Pull request by MozillaNoah**
## Before

https://user-images.githubusercontent.com/87384386/219772827-2c64ed3a-d320-4087-a95c-32c77ddf2417.mp4

## After

https://user-images.githubusercontent.com/87384386/219772437-938ca6f0-875a-4e34-86f4-cb054d85d17a.mp4

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1813753

### CODE REVIEW

**Comment by Mugurell** [comment]
From Bugzilla it seems like the expectations are:
> No matter how much I pull down the tab tray (slightly or all the way), it should close all the way to the bottom.

while in the above video it seems like a small gesture to drag down (and close) the tabstray would have it spring back to an expanded state?

I know this behavior has been historically hard to get so I would propose ignoring the current implementation and only focus on having the desired behavior in the Compose version of the tabs tray.

**Comment by MozillaNoah** [comment]
> From Bugzilla it seems like the expectations are:
> 
> > No matter how much I pull down the tab tray (slightly or all the way), it should close all the way to the bottom.
> 
> while in the above video it seems like a small gesture to drag down (and close) the tabstray would have it spring back to an expanded state?
> 
> I know this behavior has been historically hard to get so I would propose ignoring the current implementation and only focus on having the desired behavior in the Compose version of the tabs tray.

[There was some discussion below the original comment in the ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1813753#c4). The video, admittedly, is a little misleading because I didn't have the taps visible during the recording, but the tray springs back when it doesn't receive a full swipe. [Aarjav signed off on the behavior captured in the video in this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1813753#c6). 

This behavior change is part of the UX fundamentals initiative, so I think it makes sense to get this out now since it's a low effort code change, but also to minimize any potential friction when reviewing the Compose rewrite (behavior changes during that rewrite could cause red herrings when trying to compare before/after).

**Review by MatthewTighe — APPROVED** [review]
Having checked it out and tested the behavior I find it to be pretty natural in terms of my usual UX expectations on Android, so I'm adding my approval. It may be worth double-checking that @Mugurell is satisfied with the conclusion of this conversation before landing though

**Review by Mugurell — APPROVED** [review]
Tested locally, looks great!
Thanks!

**Comment by MozillaNoah** [comment]
@mergify backport releases_v111

**Pull request merged**
