### PR TITLE
Bug 1848502 - Remove unused media storage permissions in Android 13+ 

### PR DESCRIPTION
**Pull request by yrezgui**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1848502

### CODE REVIEW

**Comment by yrezgui** [comment]
### Current user experience (before change)
https://github.com/mozilla-mobile/firefox-android/assets/1113976/c50d2ee0-6809-467b-89bc-a6950de19be3

### Improved user experience (after change)
https://github.com/mozilla-mobile/firefox-android/assets/1113976/55d805dc-415a-411c-b0e5-424b5256c927

**Comment by yrezgui** [comment]
Hi @mcarare, do you know when this PR could be reviewed? Android 14 launches in coming up in the upcoming weeks, it would be great to have a Firefox release before users get the update on their phones, thanks 🙏

**Comment by mcarare** [comment]
@yrezgui Thank you for opening this PR!
Did you test the change on a device with an SD card to see if you can still upload files from external storage after this change?

**Comment by yrezgui** [comment]
@mcarare I've tested on a Pixel 7 and the emulator (which has a virtual SD card attached for each). I'll test on a Samsung device with a SD card later today. It should work though, considering `GET_CONTENT` opens the system file picker, which has access to all storage volumes

**Review by mcarare — CHANGES_REQUESTED** [review]
We still need to test that this does not lead to unintended behavior.

**Comment by mcarare** [comment]
Closing this due to lack of activity.

**Pull request closed without merging**
