### PR TITLE
Bug 1840109 - Renew telemetry probes expiring in v118

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1840109

### CODE REVIEW

**Comment by rocketsroger** [comment]
# Request for Data Collection Renewal
### Renew for 6 months
Total: 12
———
`cookie_banners.visited_setting`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/27561

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.setting_changed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/27561

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.exception_added`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28044#issuecomment-1334548056

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.exception_removed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28044#issuecomment-1334548056

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.visited_panel`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28044#issuecomment-1334548056

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.visited_re_engagement_dialog`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.opt_out_re_engagement_dialog`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.not_now_re_engagement_dialog`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`cookie_banners.allow_re_engagement_dialog`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`progressive_web_app.homescreen_tap`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/11859

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`progressive_web_app.install_tap`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/11859

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———
`recent_searches.group_deleted`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22176#issuecomment-956421788

2) When will this collection now expire?
    - 123

3) Why was the initial period of collection insufficient?
    - This is important to understand user behavior

———

**Comment by rocketsroger** [comment]
# Request for data collection review form

All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data?
  * This is important to understand user behavior.
  * Search engine related behaviors impact revenue.
2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? 
  * This will allow us to know more about user's engagement.
3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
  * There are no other alternatives. 
4. Can current instrumentation answer these questions?
  * No. 
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki. 
Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.

Measurement Description | Data Collection Category | Tracking Bug #
-- | -- | --
Tab view setting is list or grid | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/19956
An indication of whether the most visited sites are enabled to be displayed. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
An indication of whether the Jump back in section is enabled to be displayed. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
An indication of whether the recently saved section is enabled to be displayed. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
An indication of whether the Recently visited section is enabled to be displayed. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
An indication of whether Pocket is enabled to be displayed. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
A user toggles the preference for the home screen items. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
A user clicked on Customize home from the home screen menu. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
Search icon tapped: A user tapped on the search icon in history. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/23694
Search result tapped: A user tapped on the search result in history. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/23694
A user clicked on Customize home from the home screen menu. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/21239
Credit card saved: A counter of the number of credit cards that have been saved by the user. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card deleted: A counter of the number of credit cards that have been deleted by the user. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card modified: The User has modified a credit card. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card form detected: A credit card form has been detected. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card autofilled: A credit card has been autofilled to a website. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card autofill prompt shown: A credit card autofill prompt has been shown. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card autofill prompt expanded: A credit card autofill prompt has been expanded. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card autofill prompt dismissed: A credit card autofill prompt has been dismissed. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card management add tapped: the add credit card button was tapped management in credit card management. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Credit card management card tapped: A credit card was tapped management in credit card management. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/18711
Save prompt create: User saved a credit card using the autofill save prompt. | Category 2 - Interaction data | https://github.com/mozilla-mobile/android-components/issues/10343
Save prompt update: User update a credit card using the autofill save prompt. | Category 2 - Interaction data | https://github.com/mozilla-mobile/android-components/issues/10343
Save prompt shown: The credit card autofill save prompt was displayed to the user. | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/26089
An address autofill form was detected | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address autofill form was filled successfully | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address autofill prompt was displayed | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address autofill prompt was expanded | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address autofill prompt was dismissed | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address was manually saved | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address was manually edited | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
An address was manually deleted | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
The add address button was clicked | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857
User has tapped on an existing address | Category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/24857

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
  * https://dictionary.telemetry.mozilla.org/apps/fenix 
7. How long will this data be collected? Choose one of the following:
  * I want to permanently monitor this data. cgordon@mozilla.com will monitor this over time.

8. What populations will you measure?
  * All channels, all locales, all countries 
9. If this data collection is default on, what is the opt-out mechanism for users?
  * Default Glean SDK opt-out mechanism. 
10. Please provide a general description of how you will analyze this data.
  * Glean and Glam. 
11. Where do you intend to share the results of your analysis?
  * Only on Glean, Glam, and with mobile teams. 
12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
   * No third-party tools.

**Review by sarah541 — APPROVED** [review]

**Comment by eliserichards** [comment]
# Data Collection Renewal Review (to be filled by Data Stewards)

> # Request for Data Collection Renewal
> ### Renew for 6 months
> 
> Total: 12 ——— `cookie_banners.visited_setting`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1796146 - Add UI for the Cookie Banner preferences fenix#27561](https://github.com/mozilla-mobile/fenix/pull/27561)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 


1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.


> 
> ——— `cookie_banners.setting_changed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1796146 - Add UI for the Cookie Banner preferences fenix#27561](https://github.com/mozilla-mobile/fenix/pull/27561)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `cookie_banners.exception_added`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797577 - Add cookie banner handling panel to the toolbar. fenix#28044 (comment)](https://github.com/mozilla-mobile/fenix/pull/28044#issuecomment-1334548056)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `cookie_banners.exception_removed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797577 - Add cookie banner handling panel to the toolbar. fenix#28044 (comment)](https://github.com/mozilla-mobile/fenix/pull/28044#issuecomment-1334548056)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `cookie_banners.visited_panel`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797577 - Add cookie banner handling panel to the toolbar. fenix#28044 (comment)](https://github.com/mozilla-mobile/fenix/pull/28044#issuecomment-1334548056)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.


> 
> ——— `cookie_banners.visited_re_engagement_dialog`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797593 - Add re-engagement dialog for cookie banners. fenix#28405 (comment)](https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `cookie_banners.opt_out_re_engagement_dialog`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797593 - Add re-engagement dialog for cookie banners. fenix#28405 (comment)](https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `cookie_banners.not_now_re_engagement_dialog`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797593 - Add re-engagement dialog for cookie banners. fenix#28405 (comment)](https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `cookie_banners.allow_re_engagement_dialog`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Bug 1797593 - Add re-engagement dialog for cookie banners. fenix#28405 (comment)](https://github.com/mozilla-mobile/fenix/pull/28405#issuecomment-1372489596)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `progressive_web_app.homescreen_tap`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #10261: PWA Telemetry fenix#11859](https://github.com/mozilla-mobile/fenix/pull/11859)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> ——— `progressive_web_app.install_tap`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #10261: PWA Telemetry fenix#11859](https://github.com/mozilla-mobile/fenix/pull/11859)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

> 
> ——— `recent_searches.group_deleted`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22175: Telemetry for deleting a search term group from recent searches on home fenix#22176 (comment)](https://github.com/mozilla-mobile/fenix/pull/22176#issuecomment-956421788)
> 
>     2. When will this collection now expire?
>        
>        * 123
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important to understand user behavior
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
   * Yes.
2) Is the data collection covered by the existing Firefox Privacy Notice?
   * Yes.

## Result

data-review+ for all 6 month renewals.

**Comment by eliserichards** [comment]
> # Request for data collection review form
> 
> All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.
> 
>     1. What questions will you answer with this data?
> 
> 
>     * This is important to understand user behavior.
> 
>     * Search engine related behaviors impact revenue.
> 
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
>     * This will allow us to know more about user's engagement.
> 
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
>     * There are no other alternatives.
> 
> 
>     4. Can current instrumentation answer these questions?
> 
> 
>     * No.
> 
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.    
>        Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Tab view setting is list or grid 	Category 2 - Interaction data 	[mozilla-mobile/fenix#19956](https://github.com/mozilla-mobile/fenix/issues/19956)
> An indication of whether the most visited sites are enabled to be displayed. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> An indication of whether the Jump back in section is enabled to be displayed. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> An indication of whether the recently saved section is enabled to be displayed. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> An indication of whether the Recently visited section is enabled to be displayed. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> An indication of whether Pocket is enabled to be displayed. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> A user toggles the preference for the home screen items. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> A user clicked on Customize home from the home screen menu. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> Search icon tapped: A user tapped on the search icon in history. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#23694](https://github.com/mozilla-mobile/fenix/issues/23694)
> Search result tapped: A user tapped on the search result in history. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#23694](https://github.com/mozilla-mobile/fenix/issues/23694)
> A user clicked on Customize home from the home screen menu. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#21239](https://github.com/mozilla-mobile/fenix/issues/21239)
> Credit card saved: A counter of the number of credit cards that have been saved by the user. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card deleted: A counter of the number of credit cards that have been deleted by the user. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card modified: The User has modified a credit card. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card form detected: A credit card form has been detected. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card autofilled: A credit card has been autofilled to a website. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card autofill prompt shown: A credit card autofill prompt has been shown. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card autofill prompt expanded: A credit card autofill prompt has been expanded. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card autofill prompt dismissed: A credit card autofill prompt has been dismissed. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card management add tapped: the add credit card button was tapped management in credit card management. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Credit card management card tapped: A credit card was tapped management in credit card management. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#18711](https://github.com/mozilla-mobile/fenix/issues/18711)
> Save prompt create: User saved a credit card using the autofill save prompt. 	Category 2 - Interaction data 	[mozilla-mobile/android-components#10343](https://github.com/mozilla-mobile/android-components/issues/10343)
> Save prompt update: User update a credit card using the autofill save prompt. 	Category 2 - Interaction data 	[mozilla-mobile/android-components#10343](https://github.com/mozilla-mobile/android-components/issues/10343)
> Save prompt shown: The credit card autofill save prompt was displayed to the user. 	Category 2 - Interaction data 	[mozilla-mobile/fenix#26089](https://github.com/mozilla-mobile/fenix/issues/26089)
> An address autofill form was detected 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address autofill form was filled successfully 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address autofill prompt was displayed 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address autofill prompt was expanded 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address autofill prompt was dismissed 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address was manually saved 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address was manually edited 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> An address was manually deleted 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> The add address button was clicked 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> User has tapped on an existing address 	Category 2 - Interaction data 	[mozilla-mobile/fenix#24857](https://github.com/mozilla-mobile/fenix/issues/24857)
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
>     * [https://dictionary.telemetry.mozilla.org/apps/fenix   ](https://dictionary.telemetry.mozilla.org/apps/fenix%E2%80%A8)
> 
> 
>     7. How long will this data be collected? Choose one of the following:
> 
> 
>     * I want to permanently monitor this data. [cgordon@mozilla.com](mailto:cgordon@mozilla.com) will monitor this over time.
> 
> 
>     8. What populations will you measure?
> 
> 
>     * All channels, all locales, all countries
> 
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
>     * Default Glean SDK opt-out mechanism.
> 
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
>     * Glean and Glam.
> 
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
>     * Only on Glean, Glam, and with mobile teams.
> 
> 
>     12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
>     * No third-party tools.

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

* Yes, through `metrics.yaml` and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

* Yes, through the "Send Usage Data" preference in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

* Yes, this data will be permanently collected. Courtney Gordon (cgordon@mozilla.com) will be monitoring the collection permanently.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

* Category 2 - interaction data.

5) Is the data collection request for default-on or default-off?

* Default on.

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

* No. 

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**

* Yes.

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

* No.

## Result

data-review+

**Pull request merged**
