### PR TITLE
Bug 1859585 - WebExtensionSupport should update installExtensions entries on AddonManagerDelegate.onReady calls

### PR DESCRIPTION
**Pull request by rpl**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1859585

### CODE REVIEW

**Comment by rpl** [comment]
@Amejia481 this is the PR with the few more changes needed on the android components side as part of fixing [Bug 1859585](https://bugzilla.mozilla.org/show_bug.cgi?id=1859585), as anticipated I looked into adding some test coverage for the changes on this side, which is provided by the new test case added to WebExtensionSupportTest.kt, to be fair the fix is a bit spread but if I'm not mistaken this single test case should be covering all the changes included in this PR.

Let me know if I should add anything to the changelog file.

**Comment by rpl** [comment]
@Amejia481 I took a look to the apk failures and those seems to be the ones I'd expect, triggered by GeckoView build being used not yet including the new AddonManagerDelegate.onReady and build failure hit as a side effect of that:

```
GeckoEngine.kt:385:13 'onReady' overrides nothing
```

I'd expect all those to go away once the patch on the mozilla-central side has been included in a new GeckoView build and this PR running those tasks again on top of that GeckoView build.

**Comment by Amejia481** [comment]
This looks good!
Tested locally and it was working like a charm!!
Let's wait until we can land https://phabricator.services.mozilla.com/D193085

**Comment by willdurand** [comment]
(I rebased this PR to get the latest GV)

**Review by willdurand — APPROVED** [review]

**Comment by willdurand** [comment]
@Amejia481 can you please sign-off this PR? Thanks!

**Review by Amejia481 — APPROVED** [review]

**Comment by Amejia481** [comment]
Sorry, I was waiting until we get the new GV version r+ ✅ !

**Pull request merged**
