### PR TITLE
Bug 1807127 - Update Sync Device name after refreshing fxa devices

### PR DESCRIPTION
**Pull request by DreVla**
Previously when trying to update the device name, in UI, it reverted to the old one after a short delay. This patch aims to update the UI name only after refreshing synced devices. Check [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1807127#c4) for more info.

https://user-images.githubusercontent.com/32488956/230426809-5d5ae742-0e16-42d4-8eef-11c6cd9b18af.mp4

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1807127

### CODE REVIEW

**Comment by DreVla** [comment]
Since there is a slight delay after pressing ok and the name actually appearing, I would suggest a "greyed out" loading option, similar to what happens when syncing. Check the video below:


https://user-images.githubusercontent.com/32488956/233637665-7985b98b-1fa9-4239-b100-7279717aadeb.mp4

**Comment by MatthewTighe** [comment]
Are we waiting for UX approval on a "greyed out" state or are we ready to land this change? Happy to review it either way, just not entirely sure if it's still blocked.

**Comment by DreVla** [comment]
> Are we waiting for UX approval on a "greyed out" state or are we ready to land this change? Happy to review it either way, just not entirely sure if it's still blocked.

It is currently blocked, waiting on UX approval on the "greyed out" state.

**Comment by MatthewTighe** [comment]
Okay, sounds good. I'm removing the `needs-review` label for now to remove it from the queue, but please add it back once this is ready 🙂

**Comment by DreVla** [comment]
Approval has been given regarding the changes here. This PR is ready for review!

**Comment by DreVla** [comment]
@mergify backport releases_v118

**Pull request merged**
