### PR TITLE
Bug 1817439 - l10n workflows: use github-actions[bot] as authorfor uplift (sync) workflows

### PR DESCRIPTION
**Pull request by flodolo**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1817439

### CODE REVIEW

**Comment by flodolo** [comment]
Actually, I might need to verify this. I assumed `github.actor` would be a bot when running via schedule, but it might be the last person who touched the workflow.

**Review by JohanLorenzo — APPROVED** [review]
Looks good to me! Thanks for this quick fix 👍 

For the record, I didn't manage to find the logic behind the default value of `github.actor`. For instance, https://github.com/mozilla-mobile/firefox-android/pull/836 was mapped to me but I've never touched `fenix-sync-strings.yml`[1], nor have I triggered it. I wonder if I was the author of the previous commit but I wasn't either. It's so weird! 

[1] https://github.com/mozilla-mobile/firefox-android/commits/d9c08c387917e3e53963386ad53229e69d52da6e/.github/workflows/fenix-sync-strings.yml

**Comment by flodolo** [comment]
> For the record, I didn't manage to find the logic behind the default value of `github.actor`. For instance, #836 was mapped to me but I've never touched `fenix-sync-strings.yml`[1], nor have I triggered it. I wonder if I was the author of the previous commit but I wasn't either. It's so weird!

Technically, you touched it at some point.
https://github.com/mozilla-mobile/firefox-android/commit/457d88002e0dd413725fb1f99033c6ccc3a65e58

But you definitely were not the last person to do it 🤷🏼 

The [GitHub context](https://docs.github.com/en/actions/learn-github-actions/contexts) document is completely useless too, because it doesn't cover schedule

> github.actor = The username of the user that triggered the initial workflow run. If the workflow run is a re-run, this value may differ from github.triggering_actor. Any workflow re-runs will use the privileges of github.actor, even if the actor initiating the re-run (github.triggering_actor) has different privileges.

Both the replies in [this thread](https://github.com/orgs/community/discussions/25067) are also wrong, based on the behavior here.

**Comment by JohanLorenzo** [comment]
> Technically, you touched it at some point. https://github.com/mozilla-mobile/firefox-android/commit/457d88002e0dd413725fb1f99033c6ccc3a65e58

Oh you're right! I missed that.

**Comment by flodolo** [comment]
This worked
https://github.com/mozilla-mobile/firefox-android/pull/879/commits

I also realized the action log page shows the "person" who triggered a scheduled task
- `csadilek` for A-C
- `JohanLorenzo` for fenix and focus
- 
Screenshot 2023-02-18 alle 07 38 13

Which makes the criteria used by GitHub even less clear.

**Pull request merged**
