### PR TITLE
Bug 1802579 - Add extra granular media permissions for devices with Android 13 and above.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by mcarare** [comment]
This change allows any app that uses AC to target SDK 33 and still keep the capability of uploading media files.
This does not enforce targeting SDK 33, meaning an app that still targets 32 can continue to use the capability without any required changes, for both Android 13 devices and older.

**Review by jonalmeida — APPROVED** [review]
We spoke about this change offline last week - this seems like the most reasonable way forward today.

**Comment by mcarare** [comment]
Will keep this to be landed after the beta cut.

**Comment by mcarare** [comment]
note to self to update (move to 100) the changelog entry after the beta cut, before landing this.

**Comment by jonalmeida** [comment]
We can land this now! :)

**Pull request merged**
