### PR TITLE
Bug 1759519 - Fix crash when parsing malformed Content-Length

### PR DESCRIPTION
**Pull request by jackyzy823**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1759519

### CODE REVIEW

**Comment by gabrielluong** [comment]
@jonalmeida Is this something you could review? If not, please redirect - thank you

**Comment by jonalmeida** [comment]
Hey @jackyzy823 ! Thanks for the fix!

While we can accept this patch as an intermediary solution, had you considered the solution that was posted in [comment 4 on the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1759519#c4) and if so, why would the fix in Android Components be preferrable?

**Comment by jackyzy823** [comment]
Hello @jonalmeida  My fix logic is based on this line https://github.com/mozilla-mobile/firefox-android/blob/4e2cb82a71f96cafde521afc7cf4a934c21c3419/android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/DownloadState.kt#L47 . So i assume that the application built upon GeckoView already knows the headers of WebResponse are string type and not normalized.


--------------------
Gecko could provide normalized header to GeckoView, but i think that should be in a new bugzilla ticket to discuss [refactor](https://searchfox.org/mozilla-central/source/mobile/android/components/geckoview/GeckoViewStreamListener.cpp#214-248) detail .

**Review by jonalmeida — APPROVED** [review]
That sounds reasonable. Looks good to me!

**Comment by Amejia481** [comment]
@jackyzy823 it looks like there are some tests failures:

[GeckoEngineSessionTest](https://firefoxci.taskcluster-artifacts.net/Lqzew7VkT1Csr7kZyIHo4w/0/public/reports/tests/testReleaseUnitTest/classes/mozilla.components.browser.engine.gecko.GeckoEngineSessionTest.html). [contentDelegateNotifiesObserverAboutDownloadsWithEmptyContentLength](https://firefoxci.taskcluster-artifacts.net/Lqzew7VkT1Csr7kZyIHo4w/0/public/reports/tests/testReleaseUnitTest/classes/mozilla.components.browser.engine.gecko.GeckoEngineSessionTest.html#contentDelegateNotifiesObserverAboutDownloadsWithEmptyContentLength)
    [GeckoEngineSessionTest](https://firefoxci.taskcluster-artifacts.net/Lqzew7VkT1Csr7kZyIHo4w/0/public/reports/tests/testReleaseUnitTest/classes/mozilla.components.browser.engine.gecko.GeckoEngineSessionTest.html). [contentDelegateNotifiesObserverAboutDownloadsWithMalformedContentLength](https://firefoxci.taskcluster-artifacts.net/Lqzew7VkT1Csr7kZyIHo4w/0/public/reports/tests/testReleaseUnitTest/classes/mozilla.components.browser.engine.gecko.GeckoEngineSessionTest.html#contentDelegateNotifiesObserverAboutDownloadsWithMalformedContentLength)

**Comment by jackyzy823** [comment]
New arguments for `onExternalResource` introduced after this PR. Fixed the tests.

**Pull request merged**
