### PR TITLE
Bug 1823848 - Add binding classes to handle the home search selector toolbar

### PR DESCRIPTION
**Pull request by gabrielluong**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1823848

### CODE REVIEW

**Review by rocketsroger — APPROVED** [review]
Looks good.  🚢 
One nit.

**Comment by mavduevskiy** [comment]
@gabrielluong 
Reading the bug description made me wonder: how will home and onboarding fragments relate to each other?

btw, don't forget to squash before landing🙃

**Comment by gabrielluong** [comment]
> @gabrielluong Reading the bug description made me wonder: how will home and onboarding fragments relate to each other?
> 
> btw, don't forget to squash before landing🙃

There's a difference between when we want commits to be squashed versus separate. You will see in the commit logs here that each commit serves to only do one specific thing and labelled part 1, 2, etc. Functionally each commit is complete and could be landed separately if needed without breaking the build or introducing any issues.You can find other examples in our most recent history. 

Where we want commits to be squashed are when we have several commits that aren't complete on their own. For example, commit #1 is fixing the bug, commit #2 is fixing linter, commit #3 is fixing a bug with commit #1 and commit #4 is addressing reviewer feedback. If we were to look at commit #1 via git blame, we wouldn't fully get the full picture of how commit #1 is even fixing the bug because there's actually a bug in it that is only resolved in a later commit #3.

**Comment by mavduevskiy** [comment]
thanks, gl, the thing about commits makes sense!

I didn't understand your answer to my question though. How they will relate to each other in the end? Like, will they be two separate fragments, that would have a toolbar each – and that's why we want to have classes like `SearchSelectorBinding`, to be reused in both fragments.

**Comment by mavduevskiy** [comment]
> > @gabrielluong Reading the bug description made me wonder: how will home and onboarding fragments relate to each other?
> > btw, don't forget to squash before landing🙃
> 
> This relates to the first run onboarding which currently lives side by side with the home fragment.
> 
> There's a difference between when we want commits to be squashed versus separate. You will see in the commit logs here that each commit serves to only do one specific thing and labelled part 1, 2, etc. Functionally each commit is complete and could be landed separately if needed without breaking the build or introducing any issues.You can find other examples in our most recent history.
> 
> Where we want commits to be squashed are when we have several commits that aren't complete on their own. For example, commit #1 is fixing the bug, commit #2 is fixing linter, commit #3 is fixing a bug with commit #1 and commit #4 is addressing reviewer feedback. If we were to look at commit #1 via git blame, we wouldn't fully get the full picture of how commit #1 is even fixing the bug because there's actually a bug in it that is only resolved in a later commit #3.

thanks, gl, the thing about commits makes sense!

I didn't understand your answer to my question though. How they will relate to each other in the end? Like, will they be two separate fragments, that would have a toolbar each – and that's why we want to have classes like SearchSelectorBinding, to be reused in both fragments.

**Comment by gabrielluong** [comment]
Exactly, the 2 fragments (home and first run onboarding) each has the toolbar. You could see the first run onboarding by clearing your storage and observe that it has the toolbar, home menu and private mode functionality along with the onboarding cards.

**Pull request merged**
