### PR TITLE
Bug 1812960 - Added a menu item to open current page in a new private tab

### PR DESCRIPTION
**Pull request by gitstart**
The PR implement the feature where user can open a `current tab` in a `private window`

### Issue Screenshots
User can not currently open a current tab in a private window 

### Fix Screenshots
https://www.loom.com/share/3dccdf2514a14689b5b22671d93cf030

### Pull Request checklist
- [x] **Quality:** This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests:** This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog:** This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility:** The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
 - Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
 - Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

**GitHub Automation**
https://bugzilla.mozilla.org/show_bug.cgi?id=1812960

https://bugzilla.mozilla.org/show_bug.cgi?id=1812960
https://bugzilla.mozilla.org/show_bug.cgi?id=1812960
https://bugzilla.mozilla.org/show_bug.cgi?id=1812960
https://bugzilla.mozilla.org/show_bug.cgi?id=1812960

### CODE REVIEW

**Review by Mugurell — COMMENTED** [review]
Thank you for your contribution and the attention to details.

Regarding the scenario described in the Bugzilla ticket - "Nowadays most websites clutter the screen with banners to accept their cookies" Fenix recently gained the "Cookie banner reduction" feature that will help with just this! Will update the Bugzilla ticket about this.

The 3dot menu is very important for the application and as such any changes need to be approved by UX and product. Will keep you posted with the discussions result.

**Comment by gitstart** [comment]
> Thank you for your contribution and the attention to details.
> 
> Regarding the scenario described in the Bugzilla ticket - "Nowadays most websites clutter the screen with banners to accept their cookies" Fenix recently gained the "Cookie banner reduction" feature that will help with just this! Will update the Bugzilla ticket about this.
> 
> The 3dot menu is very important for the application and as such any changes need to be approved by UX and product. Will keep you posted with the discussions result.

Thank you @Mugurell for the comment🙏.. Will be waiting for your reply. 🚀

**Comment by lime124** [comment]
we are currently working on the IA of the menu in our apps. / cc @ewachowiak for consideration as part of this work.

**Comment by amedyne** [comment]
Thanks so much for this really interesting idea. We are currently working on something that we hope may address some of the issues with cookies that this PR was trying to address. Thus we will close this PR.

**Pull request closed without merging**
