### PR TITLE
 Bug 1832008  - [MozillaOnline] Export firefox account personal info and save the file

### PR DESCRIPTION
**Pull request by rxumoz**
Due to the requirement from authorities in China, there will be several PR about MozillaOnline builds modifications in the next few days.

This PR export the firefox account personal info (email, displayName, avatar, device) as a txt file and save it.

https://bugzilla.mozilla.org/show_bug.cgi?id=1832008
https://bugzilla.mozilla.org/show_bug.cgi?id=1832008
https://bugzilla.mozilla.org/show_bug.cgi?id=1832008
https://bugzilla.mozilla.org/show_bug.cgi?id=1832008
https://bugzilla.mozilla.org/show_bug.cgi?id=1832008

### CODE REVIEW

**Comment by rocketsroger** [comment]
Why are we moving/saving account information as plaintext?

**Review by rocketsroger — CHANGES_REQUESTED** [review]
Tagging this with request for changes for more discussion.

**Comment by rxumoz** [comment]
> Why are we moving/saving account information as plaintext?

Authorities in China require the apps with "Account" service to have a function for users to export the account info. I think it maybe it is not as useful since our account info is really simple, but the requirement is for all apps with "account".

**Comment by gabrielluong** [comment]
:construction: **Pull Requests Cleanup:** :construction: Hi, we're looking to reduce the amount of pull request overhead we currently have. This pull request has been a WIP without any recent activities. Please feel free to reopen this PR at any point when you want to have your changes reviewed. Thank you for your contribution!

**Pull request closed without merging**
