### PR TITLE
Status check openTopSiteInANewPrivateTabTest UI test

### PR DESCRIPTION
**Pull request by AndiAJ**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by AndiAJ** [comment]
After doing a branch reset to #5065 both UI tests worked properly. ✅ 
On the other hand, after doing a reset to #4646 they started to be flaky or even fail. ❌ 

As seen on main, after opening the top sites in a new private tab the PB home screen remains displayed, and the top site isn't actually loaded in a new private tab.

`openSponsoredShortcutInPrivateTabTest` [Firebase link from this status check](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8821613435499824247/executions/bs.c65ba0aa910a31f9/videos)
`openTopSiteInANewPrivateTabTest` [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6255382460841597178/executions/bs.7985f5a9b6808534/videos)

`openSponsoredShortcutInPrivateTabTest` [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1874140) containing the Firebase test runs from main
`openTopSiteInANewPrivateTabTest` [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1874116) containing the Firebase test runs from main

@MatthewTighe mentioned in the [Bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1861459#c1) that there might be some problems with the top sites being opened in a new private tab.

Mostly likely these 2 UI tests might have found a problem.

This seems to be happening only on Firebase, I wasn't able to reproduce locally neither by running the automated UI tests on an emulator and physical device, nor doing the steps manually

**Comment by MatthewTighe** [comment]
👋 hey there @AndiAJ, thanks for bringing this to my attention! I have a potential fix prepared in https://github.com/mozilla-mobile/firefox-android/pull/5150. 

I tried to replicate what I assumed was your test orchestration setup to re-run those tests repeatedly to test for flakiness, but I'm not familiar with the tooling. Will you let me know if that looks like it's solved the issue, and I'll file a bug and merge the patch?

**Comment by gabrielluong** [comment]
Hi @AndiAJ, I am cleaning up our current Pull Request backlog in preparation for the monorepo migration. Is this something you're still looking to push forward with to get review and landed in the immediate term?

**Comment by MatthewTighe** [comment]
I believe this patch was opened to demo some test failures on the https://github.com/mozilla-mobile/firefox-android/pull/4646, and so am closing it as I think it's served its purpose there already.

**Pull request closed without merging**
