### PR TITLE
Bug 1822750 - Add option to open default browser help page in custom tab

### PR DESCRIPTION
**Pull request by rahulsainani**
### What
As the Juno Onboarding Cards include a CTA to make firefox the default browser, it needs to use Activity.openSetDefaultBrowserOption() extension function. This currently defaults to opening a new tab. As the user would be in the Juno Onboarding Flow, a new tab would not work. So this PR adds option to open default browser help page in a custom tab.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1822750

### CODE REVIEW

**Review by t-p-white — APPROVED** [review]
lgtm 👍

**Comment by Mugurell** [comment]
What happens if from a custom tab users then tap on the menu to choose "Open in browser"?

**Comment by rahulsainani** [comment]
> What happens if from a custom tab users then tap on the menu to choose "Open in browser"?



> What happens if from a custom tab users then tap on the menu to choose "Open in browser"?

Good question! It opens the new tab, that's not what we want, is there a way to disable that from the caller?

**Comment by Mugurell** [comment]
> > What happens if from a custom tab users then tap on the menu to choose "Open in browser"?
> 
> Good question! It opens the new tab, that's not what we want, is there a way to disable that from the caller?

Don't think so.
We can add options but I don't think we can remove the default ones.
https://developer.chrome.com/docs/android/custom-tabs/integration-guide/
Given that a custom tab opens in the default browser which may not be Fenix it doesn't seem like we can safely avoid this.

Not sure about the overall UX but maybe we could introduce in the app another functionality for showing one webpage at a time, similar to a custom tab but implemented really through just a fragment/dialog showing an `EngineView` in private mode (so that history etc would not be kept)
This scenario would be useful in other similar scenarios also.
Personally I would really like something like a modal dialog with a bit of empty space around it to suggest that the page the user is seeing is somewhat temporary, in-app content and not part of the browsing UX.

image

**Comment by Piratesarereal** [comment]
Yup, I understand, trying to be mindful of unintentionally leaking users out of onboarding if they discover this by themselves, they would be able to skip onboarding entirely. I am not sure about the complexity of petru's suggested implementation, but I would say it can be tabled for now. But I wouldn't close this issue, because it can still possibly cause user leaks from onboarding. We can come back to this post MVP implementation of Android Onboarding for Juno.

**Comment by rahulsainani** [comment]
Thanks @Piratesarereal We've created this [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1823892) to solve the issue of leaking out the users out of onboarding, and that's been worked on. 
So now, the caller can use this to show the SUMO page in a custom tab and when the mentioned ticket is done, the caller can also pass in the flag to hide the "Open in Firefox" menu item. @Mugurell wdyt?

**Comment by Mugurell** [comment]
> Thanks @Piratesarereal We've created this [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1823892) to solve the issue of leaking out the users out of onboarding, and that's been worked on. So now, the caller can use this to show the SUMO page in a custom tab and when the mentioned ticket is done, the caller can also pass in the flag to hide the "Open in Firefox" menu item. @Mugurell wdyt?

LGTM.
We've discussed "offline" and this seems to be a great middle ground approach for cases in which we need to have a modal for displaying webpages.
Not sure if this behavior of hiding that we're using a custom tab should be used for all the other similar scenarios (being able to switch to a full tab which would allow for functionalities like history, bookmarks, collections, sharing has advantages) but in this case where we need to prevent the user exiting the onboarding early (which could be possible through a custom tab's "open in .." menu option) it seems like a nice solution.

**Pull request merged**
