### PR TITLE
Bug 1567912 - Add beetmover-bundle task

### PR DESCRIPTION
**Pull request by gbrownmozilla**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1567912

### CODE REVIEW

**Comment by gbrownmozilla** [comment]
`taskgraph target-graph -p taskcluster/test/params/main-repo-cron-nightly.yml --diff` produces:
```
-beetmover-fenix-nightly
-beetmover-focus-nightly
+beetmover-aab-fenix-nightly
+beetmover-aab-focus-nightly
+beetmover-apk-fenix-nightly
+beetmover-apk-focus-nightly
```

**Review by jcristau — COMMENTED** [review]
Is there a particular reason this can't re-use the existing beetmover-apk task, by just adding the signing-bundle dependency, instead of adding a whole new kind?

**Comment by gbrownmozilla** [comment]
I initially went with the beetmover-apk/beetmover-bundle kinds because that seemed consistent with build-apk/build-bundle, signing-apk/signing-bundle, etc. -- and it was simple and easy.

Maybe my dependency-fu is not up to the task, but I find I run into trouble if I try to make these one kind. Would a beetmover-android-app kind have both signing-apk and signing-bundle as kind-dependencies? How do I then make the apk task use only apk upstream artifacts and the aab task use only aabs?

**Comment by jcristau** [comment]
What I had in mind is a single beetmover task per build type that pulls in and uploads both aab and apks, something like https://github.com/jcristau/firefox-android/commit/bc425017a869a2e6245f904cc76d112e8944725e

**Comment by gbrownmozilla** [comment]
Sure, that works for me (and makes the patch much simpler).

**Review by jcristau — APPROVED** [review]

**Comment by gbrownmozilla** [comment]
Oops - the PR title ended up being misleading. 

I should have changed it to something like "Include AABs in beetmover task"

**Pull request merged**
