### PR TITLE
Bug 1816421 - Disable fission performance tests

### PR DESCRIPTION
**Pull request by 92kns**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1816421

### CODE REVIEW

**Comment by 92kns** [comment]
https://github.com/mozilla-mobile/firefox-android/pull/1014/checks?check_run_id=11665730194

I see an insufficient scope error. do pull requests not have the same scope?

**Comment by gmierz** [comment]
@92kns I think it's because we might not have permissions.

@JohanLorenzo would you be able to help with this? We were able to trigger the performance tests on PRs in the fenix repo, but we're unable to here for some reason.

**Comment by csadilek** [comment]
@gmierz @92kns I've updated your (the perf. teams) permissions now. If you rebase / push again, the checks should run.

**Comment by 92kns** [comment]
thanks @csadilek !

**Comment by 92kns** [comment]
Ah, looks like it is still failing https://github.com/mozilla-mobile/firefox-android/pull/1014/checks?check_run_id=11670367244

**Comment by csadilek** [comment]
@JohanLorenzo Can you take a look at this error next? :) Repo permissions should be OK now for the perf. team.

**Comment by JohanLorenzo** [comment]
I see what's going on. Fix is incoming in [bug 1820117](https://bugzilla.mozilla.org/show_bug.cgi?id=1820117).

**Comment by JohanLorenzo** [comment]
Decision task is back working and it scheduled the perf tests

**Comment by 92kns** [comment]
Thanks a lot @JohanLorenzo !
@gmierz Looking at the decision task it looks like only nofis is running now
https://github.com/mozilla-mobile/firefox-android/pull/1014/checks?check_run_id=11748457534

Any need to wait for all these to finish running? Otherwise I can remove [github-pull-request] and re commit

**Review by gmierz — APPROVED** [review]
r+ thanks! Changes look good. And thanks @JohanLorenzo @csadilek for the help!

**Comment by gmierz** [comment]
@92kns +1 on undoing the testing changes now

**Comment by 92kns** [comment]
@JohanLorenzo would you be able to merge this? Merging is blocked for me as I am not an authorized user

**Comment by JohanLorenzo** [comment]
Hey @92kns! No one is meant to manually merge PRs on the `firefox-android` repo. Instead, Mergify takes care of it. You can tell Mergify by setting one of the `needs landing` PR labels

image

**Comment by 92kns** [comment]
Ah that's awesome! Thanks @JohanLorenzo  I will try that out

**Comment by 92kns** [comment]
I see the warning
`Rule: Needs landing - Rebase (queue) — Pull request must be rebased manually `
But my latest pushes really messed something up 😅 sorry, looking into it

**Comment by 92kns** [comment]
@JohanLorenzo how can I fix this message? `The pull request rule doesn't match anymore` 
https://github.com/mozilla-mobile/firefox-android/pull/1014/checks?check_run_id=11795425577

**Comment by JohanLorenzo** [comment]
If I'm not mistaken, this message will go away once the PR is on the merge train. At the moment, it's still in the queue waiting for https://github.com/mozilla-mobile/firefox-android/pull/882 to be merged first ⬇️ 

image

**Pull request merged**
