### PR TITLE
Bug 1807307 - Re-land disabling LeakCanary in CI fuzzy testing builds

### PR DESCRIPTION
**Pull request by jonalmeida**
The original changeset (5562faa97b3986e436bf76e29fe002499c7ad59f) caused CI failures because of YAML parsing the multi-line XML contents.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1807307

### CODE REVIEW

**Comment by jonalmeida** [comment]
I ran my [changes locally](https://taskcluster-taskgraph.readthedocs.io/en/latest/howto/run-locally.html) which produced no errors. The only difference between in this change from https://github.com/mozilla-mobile/firefox-android/pull/2213 is that I've moved the `path` attribute above because I noticed some YAML parsers seemed to incorrectly highlight it (even though no errors were noted).

**Review by ahal — APPROVED** [review]
Lgtm!

**Comment by jonalmeida** [comment]
Thanks for the review!

Let's land this early now when it's early in the week, and see if everything goes fine, or if we need to back it out again.

cc: @AaronMT

**Comment by jonalmeida** [comment]
Well that [failed](https://treeherder.mozilla.org/logviewer?job_id=424395053&repo=firefox-android&lineNumber=145) miserably. 😄 

Backing out.

**Pull request merged**
