### PR TITLE
Bug 1806798 - Better handle longer filenames in download confirmation dialog.

### PR DESCRIPTION
**Pull request by mcarare**
Also add a max height for the file name, so the download button is always visible.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

Fenix / Focus outcome after the fix.

Note that the scrollbar is visible only when scrolling and only if the filename text view height is over the 160 dp max height (this could be changed if UX considers another value more appropriate).

  

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1806798

### CODE REVIEW

**Comment by mcarare** [comment]
The same fix is applied to the "Open download" dialog in Fenix here: https://github.com/mozilla-mobile/fenix/pull/28512

**Review by zmckenney — APPROVED** [review]
The code looks good

**Comment by lime124** [comment]
thanks @mcarare - i asked someone from my team to take a look at it today.

**Comment by mcarare** [comment]
@lime124 Thank you!

**Review by aarjavpandya — COMMENTED** [review]
Unable to test with files name longer than 240 character count[PFA]. All the places I am using to test it, auto-truncates the file's name even if I create one with a long name. Because of this I am not able to test the scroll feature. 

Also I am unsure how to preview the download dialog from bottom of the screen, I could only test it for center of the screen. 

Screenshot_20230119-134049

**Comment by mcarare** [comment]
Also adding a video with the interaction in Focus.


https://user-images.githubusercontent.com/48995920/213756371-c67010b3-e420-4572-94f6-67b07f6b9659.mp4

**Comment by mcarare** [comment]
video with interaction on Fenix (includes the open dialog in https://github.com/mozilla-mobile/fenix/pull/28512). 


https://user-images.githubusercontent.com/48995920/213771863-8b48dc9d-7361-4365-bfbe-e8b877a57287.mp4

**Review by aarjavpandya — APPROVED** [review]
The new implementation works and no known issues are visible. 

@mcarare thank you for confirming 160 dp max height for both download and open dialog boxes for the fenix implementation. The focus implementation works fine too. 

Thank you.

**Pull request merged**
