### PR TITLE
Bug 1876024 - Request screenshot thumbnail when onSwipeStarted

### PR DESCRIPTION
**Pull request by jackyzy823**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1876024

### CODE REVIEW

**Comment by t-p-white** [comment]
🚗 drive-by: @jackyzy823 could you fix the failing detekt line please? 🙏

**Comment by t-p-white** [comment]
Thanks @jackyzy823! While trying out this patch, I'm noticing a flash/ghost image of previous captures on some swipes, please see video for demo. At the moment, I'm not entirely sure whether this is an existing bug that was not as noticeable given the UI jank or if this fix is causes

https://github.com/mozilla-mobile/firefox-android/assets/1833156/9b82796f-ee79-45ca-a949-e9356524ab0c

**Comment by jackyzy823** [comment]
Hi @t-p-white , sorry for the late response.

I think the visual glitch might not be introduced by this PR.

During my personal usage, i have observed the behavior before. ( This might caused by the switch of thumbnail and real webview ?)

I'll keep an eye on this problem.

**Comment by t-p-white** [comment]
Thanks for the reply @jackyzy823, apologies also for the delay. Let's land this as-is, and we can look at how to fix the visual glitch in another bug.

**Pull request merged**
