### PR TITLE
Bug 1850933 - Override onProvideAssistContent in ExternalAppBrowserActivity

### PR DESCRIPTION
**Pull request by jackyzy823**
I'm not sure how to add a test.  Since the function `onProvideAssistContent` in `HomeActivity` have no test either.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1850933

### CODE REVIEW

**Comment by jonalmeida** [comment]
@jackyzy823 have you considered adding this to the `HomeActivity`? It may be scope creep, but I think that would give the same support to the main Fenix browser too, right?

Sorry, I haven't looked too deeply into this API yet, but thought you might have done some research already and felt it might be better to ask. 🙂

**Comment by jackyzy823** [comment]
Hello @jonalmeida 

`HomeActivity` already have its own implmentation of `onProvideAssistContent`
See : https://github.com/mozilla-mobile/firefox-android/blob/main/fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L604-L608

---------------------------------


So without this patch , in custom tab, `HomeActivity` (because it is the base class ) 's `onProvideAssistContent` called , not custom tab's own Activity's `onProvideAssistContent` called.

**Comment by rahulsainani** [comment]
@jackyzy823 Thanks for the patch. I tested it and it works well. 

Unrelated to this patch, we really need to fix the inheritance tree of `ExternalAppBrowserActivity` and switch to composition for common functionality rather than inheriting from `HomeActivity`.

@jonalmeida The [PR](https://github.com/mozilla-mobile/firefox-android/pull/903) that added this functionality in `HomeActivity` that sets the `outContent.webUri` to the current selected tab for your reference.

**Comment by rahulsainani** [comment]
bors try

**Review by rahulsainani — APPROVED** [review]

**Pull request merged**
