### PR TITLE
Bug 1835665 - Unify FocusDependencies with AC's DependenciesPlugin

### PR DESCRIPTION
**Pull request by gabrielluong**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1835665

### CODE REVIEW

**Review by rvandermeulen — APPROVED** [review]
`mockwebserver_focus` and `preferences_focus` make me sad, but I get the need for now. LGTM!

**Comment by gabrielluong** [comment]
@gbrownmozilla I am looking for a review on the taskcluster related changes. If you have any questions, let me know. If there's someone else who should also be included in reviewing the taskcluster changes, please also forward a review request. Thank you!

**Comment by gabrielluong** [comment]
@mcarare Also, looking for an approval from you before we move ahead with this. The alternative is to still convert `FocusDependencies` into a plugin and maintain the separation.

**Review by gbrownmozilla — APPROVED** [review]
Looks good to me.

**Comment by gabrielluong** [comment]
Putting this draft to revisit some ideas of only keeping AC related dependencies inside of ComponentsDependencies. What I have heard from @jonalmeida and @csadilek is that we should still maintain a separation so that AC is still its own independent project (eg, it only knows about its own dependencies, it's okay for Focus to know about AC, but not the other way around). This means we want to only utilize what is common from ComponentsDependencies and still maintain specific app (Focus, Fenix) dependencies in a FocusDependencies.

**Comment by gabrielluong** [comment]
Closing in favor of https://github.com/mozilla-mobile/firefox-android/pull/2462

**Pull request closed without merging**
