### PR TITLE
Bug 1853107 - Fix a race condition on CreateEngineSession

### PR DESCRIPTION
**Pull request by jackyzy823**
Previously on #5257 

Follow the condition logic according to @MatthewTighe 's review: https://github.com/mozilla-mobile/firefox-android/pull/5257#discussion_r1501135176

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1853107

### CODE REVIEW

**Comment by gabrielluong** [comment]
@MatthewTighe is this something you can take on as the reviewer?

**Comment by MatthewTighe** [comment]
Yep, I can review this one

**Review by MatthewTighe — APPROVED** [review]
Alright, think I'm ready to move forward with this one. Let's wait until Monday to land though. Thanks again for your patience and help in working through this!

**Comment by MatthewTighe** [comment]
bors try

**Comment by MatthewTighe** [comment]
bors try

**Comment by MatthewTighe** [comment]
Looks like `bors` is finally offline, so we'll have to switch back to our [old method of running UI tests](https://github.com/mozilla-mobile/firefox-android/blob/main/fenix/docs/Guide-to-merging-contributor-PRs.md#process-for-running-ui-tests-on-a-contributor-pr). I've created https://github.com/mozilla-mobile/firefox-android/pull/5902 to start the UI tests

**Comment by MatthewTighe** [comment]
@jackyzy823 I think these tests will pass once you rebase on main - or we can land my copy of the patch which I already rebased. Up to you, if you have any preference

**Comment by jackyzy823** [comment]
@MatthewTighe Hello, you could land your copy of the patch. :)

**Comment by MatthewTighe** [comment]
Gotcha, will do. Thanks again for all your help and work on this one!

**Pull request closed without merging**
