### PR TITLE
Bug 1821261 – Enables unified search on nightly

### PR DESCRIPTION
**Pull request by mavduevskiy**
created a different branch with a different approach suggested by @gabrielluong [here](https://github.com/mozilla-mobile/firefox-android/pull/1180#issuecomment-1463025531).

I kept using the preference settings (it actually made fixing UI tests much easier, thanks again, gl, for the tip). I changed the pref name to enable unified search for had it disabled manually, to address Roger's concern as well.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1821261

### CODE REVIEW

**Comment by gabrielluong** [comment]
This looks good to me. Will leave the final review to @rocketsroger

**Review by rocketsroger — COMMENTED** [review]
Looks good, couple of questions:

1. Expected changes in app/.experimenter.yaml, but don't see it here.
2. The change looks like it's authored by Johan, Is this some weirdness merging with main?

**Comment by JohanLorenzo** [comment]
I don't know what happened there. I'd recommend `git commit --amend --reset-author`[1] to make my name disappear. 

[1] https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---reset-author

**Review by rocketsroger — APPROVED** [review]
🚢 Thanks!

**Pull request merged**
