### PR TITLE
Bug 1807573 - Add field to set custom search engine suggestion URL

### PR DESCRIPTION
**Pull request by ajhall**
Add a field to the "save search engine" fragment to allow users to add a custom URL to provide search auto-suggestions. If this field is left blank, the custom search engine feature will function exactly as it did before this change.

I don't know if you'd like a changelog entry for this. Please let me know.

* Previous attempt at this same PR: https://github.com/mozilla-mobile/fenix/pull/25402
* Original GitHub issue: https://github.com/mozilla-mobile/fenix/issues/7866.
* Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807573

### Screenshots
Screenshot_20230702-134056
Screenshot_20230702-134121

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1807573

### CODE REVIEW

**Comment by MatthewTighe** [comment]
This looks awesome from my perspective. Thanks for taking the time to add this feature and especially for your patience in getting it landed (across repos even)! I see that the needs-UX and needs-Product requests were never fulfilled in our previous repo. I think we could probably get this in without a full UX pass since it's following the precedent established on the screen, but I do think it's worth running it past product conceptually. I'll see if I can get that fast-tracked a bit.

In the meantime, tagging @mavduevskiy for review as this screen will be a little more familiar for him.

**Comment by MatthewTighe** [comment]
This has received sign-off from product and is just waiting for UX approval on the added strings. Waiting on a PTO return and then we'll be good to review this. Thanks again for your patience!

**Comment by ewachowiak** [comment]
Weighing in with the content design/UX recommendations for the string changes here:

New string for form label:
> Search suggestion API (optional)

Placeholder text for form field:
> Search suggestion API link

Explainer text below form field:
> Replace query with "%s". Example: http://suggestqueries.google.com/complete/search?client=firefox&q=%s. [Learn more](Use same help center article URL as the above form field)

@MatthewTighe Can you please verify that the example URL above is a correct example? if not, please replace. 

We will update the help center article with info about this field when it releases. Thanks for the contribution!

**Comment by MatthewTighe** [comment]
The URL looks good to me, thanks for your help!

**Comment by ajhall** [comment]
Screenshot_20230725-230311~2

Thanks for the review! Here's a screenshot with the updated strings.

**Review by MatthewTighe — COMMENTED** [review]
This is looking good to me! Please just squash your commits and we can get this landed

**Comment by ajhall** [comment]
OK, squashed down to 1 commit and rebased onto the latest version of `main`.

**Review by MatthewTighe — APPROVED** [review]
Awesome, LGTM. Thanks again for your contribution and your outstanding patience in seeing this through!

**Comment by MatthewTighe** [comment]
bors try

**Pull request merged**
