### PR TITLE
Bug 1845104 - Open links in the current app from a CustomTab even when OpenInApp settings is set to 'never'

### PR DESCRIPTION
**Pull request by titooan**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1845104

### CODE REVIEW

**Review by rocketsroger — APPROVED** [review]
Looks great! 🚢

**Comment by rvandermeulen** [comment]
@titooan This has real-looking test failures.

**Comment by rocketsroger** [comment]
Not sure about the UI test failures. I can't see the actual failures in Firebase but looking at the log output it seems unrelated to his change.

**Comment by AaronMT** [comment]
> Not sure about the UI test failures. I can't see the actual failures in Firebase but looking at the log output it seems unrelated to his change.

@titooan and @rocketsroger have `moz-focus-android` access. Also visible now in logs https://github.com/mozilla-mobile/firefox-android/pull/2990/checks?check_run_id=15337088821

Code change here seems to affect Focus with failures in  `java.lang.IllegalStateException: Fragment BrowserFragment`

**Comment by titooan** [comment]
Thanks @AaronMT and @rvandermeulen for the heads up. I fixed the issue, it should be good now

**Pull request merged**
