### PR TITLE
Bug 1870668 - Remove the `mozac_feature_addons_authors` string

### PR DESCRIPTION
**Pull request by willdurand**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues. **See:** https://github.com/mozilla-mobile/reference-browser/pull/2625

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1870668

### CODE REVIEW

**Comment by sarah541** [comment]
It is also being used in [reference-browser](https://searchfox.org/mozilla-mobile/source/reference-browser/app/src/main/res/layout/activity_add_on_details.xml#32). We need to change here too

**Review by sarah541 — CHANGES_REQUESTED** [review]
It is also being used in [reference-browser](https://searchfox.org/mozilla-mobile/source/reference-browser/app/src/main/res/layout/activity_add_on_details.xml#32). We need to change here too

**Comment by willdurand** [comment]
> It is also being used in [reference-browser](https://searchfox.org/mozilla-mobile/source/reference-browser/app/src/main/res/layout/activity_add_on_details.xml#32). We need to change here too

That's a different project/repo, the patch for it is linked in the PR description above so I am not sure what the r- means here.

**Review by sarah541 — APPROVED** [review]
Sorry my bad! LGTM

**Pull request merged**
