### PR TITLE
Bug 1815001 - Enable the Tabs Tray to Compose rewrite in Nightly

### PR DESCRIPTION
**Pull request by MozillaNoah**
This PR has gone through 4 CI checks and it's passed as all green. We have also received the OK from UX + Product to land this in Nightly, and QA's status is green as well. The plan is to enable the rewrite in Nightly, continue working on UI test conversion and adding the remaining missing functionality (CFRs and Tab reordering), and monitor the stability for the next several weeks before doing a round of consensus and metrics gathering before enabling this in Beta (and eventually doing the same for Release).

For more details, please check the [mega meta](https://bugzilla.mozilla.org/show_bug.cgi?id=1810775).

### Note on tab reordering missing
This is ongoing work from Alex and Mihai, and our goal is for that work to land within 1-2 weeks of this being enabled. While this is functionality existing in production, the reordering work in Compose has proven to be very complicated, and we didn't want to rush a bad implementation, nor hold off on the rewrite when we feel we're close to a working solution. Nevertheless, it is a hard requirement for Beta that this feature be included.

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1815001

### CODE REVIEW

**Comment by MozillaNoah** [comment]
CI pass 1: ✅

**Comment by MozillaNoah** [comment]
CI pass 3: ✅

**Review by MatthewTighe — APPROVED** [review]

**Review by Alexandru2909 — APPROVED** [review]

**Pull request merged**
