### PR TITLE
Bug 1807073 - Prevent pull-to-refresh after scrolling down

### PR DESCRIPTION
**Pull request by hiikezoe**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1807073

### CODE REVIEW

**Comment by jonalmeida** [comment]
Hi @hiikezoe! Today, @titooan and I tested your patch and were still able to reproduce the bug where dragging the page down and then up causes pull-to-refresh to be triggered when it shouldn't.

While doing this, we also explored the idea of enabling PTR only when we're at the top of the page and disabling it as soon as we leave the top in the same motion. This is our patch that does not working but this the idea, do you think it would be useful for your own investigation? We will continue this investigation async as well, but let us know if there is anything else we can help with. 🙂 

<details>

<summary>Example patch</summary>

```diff
diff --git a/android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt b/android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
index 0d59359a5c..369b3def2a 100644
--- a/android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
+++ b/android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
@@ -12,6 +12,7 @@ import androidx.core.view.NestedScrollingChild
 import androidx.core.view.NestedScrollingChildHelper
 import androidx.core.view.ViewCompat
 import mozilla.components.concept.engine.InputResultDetail
+import mozilla.components.support.base.log.logger.Logger
 import org.mozilla.geckoview.GeckoView
 
 /**
@@ -28,12 +29,16 @@ import org.mozilla.geckoview.GeckoView
 @Suppress("ClickableViewAccessibility")
 open class NestedGeckoView(context: Context) : GeckoView(context), NestedScrollingChild {
 
+    private val logger = Logger("NestedGeckoView")
+
     @VisibleForTesting
     internal var lastY: Int = 0
 
     @VisibleForTesting
     internal val scrollOffset = IntArray(2)
 
+    private var isOnTop: Boolean? = null
+
     private val scrollConsumed = IntArray(2)
 
     @VisibleForTesting
@@ -61,6 +66,21 @@ open class NestedGeckoView(context: Context) : GeckoView(context), NestedScrolli
 
         when (action) {
             MotionEvent.ACTION_MOVE -> {
+                // not-first motion event
+                if (isOnTop == true) {
+                    logger.info("isOnTop == true")
+                    super.onTouchEventForDetailResult(event).accept {
+                        isOnTop = !inputResultDetail.canScrollToTop()
+                        logger.info("isOnTop: $isOnTop")
+                        if (isOnTop == false) {
+                            logger.info("isOnTop == false")
+                            parent?.requestDisallowInterceptTouchEvent(true)
+                        }
+                    }
+                    event.recycle()
+                    return true
+                }
+
                 val allowScroll = !shouldPinOnScreen() && inputResultDetail.isTouchHandledByBrowser()
 
                 var deltaY = lastY - eventY
@@ -81,9 +101,13 @@ open class NestedGeckoView(context: Context) : GeckoView(context), NestedScrolli
             }
 
             MotionEvent.ACTION_DOWN -> {
-                // A new gesture started. Ask GV if it can handle this.
+                // first motion event
+                isOnTop = null
                 inputResultDetail = InputResultDetail.newInstance(false)
                 parent?.requestDisallowInterceptTouchEvent(true)
+
+                // A new gesture started. Ask GV if it can handle this.
+                logger.info("ACTION_DOWN start: ${inputResultDetail.asString()}")
                 updateInputResult(event)
 
                 nestedOffsetY = 0
@@ -126,7 +150,12 @@ open class NestedGeckoView(context: Context) : GeckoView(context), NestedScrolli
                     it?.scrollableDirections(),
                     it?.overscrollDirections(),
                 )
-                parent?.requestDisallowInterceptTouchEvent(false)
+
+                logger.info("ACTION_DOWN GV result: ${inputResultDetail.asString()}")
+                isOnTop = !inputResultDetail.canScrollToTop()
+                if (isOnTop == true) {
+                    parent?.requestDisallowInterceptTouchEvent(false)
+                }
                 startNestedScroll(ViewCompat.SCROLL_AXIS_VERTICAL)
             }
     }
@@ -173,3 +202,10 @@ open class NestedGeckoView(context: Context) : GeckoView(context), NestedScrolli
         return childHelper.dispatchNestedPreFling(velocityX, velocityY)
     }
 }
+
+internal fun InputResultDetail.asString(): String {
+    return "HandledByBrowser: ${isTouchHandledByBrowser()}, " +
+        "Unhandled: ${isTouchUnhandled()}, " +
+        "HandledByWebsite: ${isTouchHandledByWebsite()}, " +
+        "HandlingUnknown: ${isTouchHandlingUnknown()}"
+}
diff --git a/fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt b/fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
index 264b9dc719..941cb9af76 100644
--- a/fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
+++ b/fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
@@ -257,7 +257,7 @@ open class FenixApplication : LocaleAwareApplication(), Provider {
             val megazordSetup = finishSetupMegazord()
 
             setDayNightTheme()
-            components.strictMode.enableStrictMode(true)
+            //components.strictMode.enableStrictMode(true)
             warmBrowsersCache()
 
             initializeWebExtensionSupport()
```

</details>

**Comment by hiikezoe** [comment]
Of course I am happy to defer the bug to you guys!

I think your approach should also work (that's said I think your approach would be mostly same as mine eventually)

One caveat I should tell you guys is that if the web content has a touchmove event listener, Gecko doesn't respond the initial ACTION_DOWN event until the first ACTION_MOVE event was (or wasn't) consumed by the event handler. In the case, the result of onTouchEventForDetailResult() for the first ACTION_MOVE is, IIRC, same as the initial ACTION_DOWN event result, thus even if the web content has been started scrolling by the ACTION_MOVE, `canScrollToTop()` would be false.

**Comment by jonalmeida** [comment]
> Of course I am happy to defer the bug to you guys!
> 
> I think your approach should also work (that's said I think your approach would be mostly same as mine eventually)

@hiikezoe we don't have a strong preference on which approach we go with, I think, although for now, both of the solutions still reproduce the bug, so we're not completely sure we know where to go next with this investigation. In your testing, does your patch no longer reproduce the bug?

> One caveat I should tell you guys is that if the web content has a touchmove event listener, Gecko doesn't respond the initial ACTION_DOWN event until the first ACTION_MOVE event was (or wasn't) consumed by the event handler. In the case, the result of onTouchEventForDetailResult() for the first ACTION_MOVE is, IIRC, same as the initial ACTION_DOWN event result, thus even if the web content has been started scrolling by the ACTION_MOVE, `canScrollToTop()` would be false.

Thank you! This is really helpful and aligns with what we were seeing our testing.

**Comment by hiikezoe** [comment]
> > Of course I am happy to defer the bug to you guys!
> > I think your approach should also work (that's said I think your approach would be mostly same as mine eventually)
> 
> @hiikezoe we don't have a strong preference on which approach we go with, I think, although for now, both of the solutions still reproduce the bug, so we're not completely sure we know where to go next with this investigation. In your testing, does your patch no longer reproduce the bug?

I don't have any preference for either approach either, but I would prefer to defer the bug to you guys. :)
Yeah, it works on my end, but I tested it on Android emulator where it feels kinda jittering on scrolling so that it's possible the change doesn't completely fix the issue. Let me double-check tomorrow.

**Comment by hiikezoe** [comment]
Okay, I did double-check both on Android Emulator and on Pixel 3. This change works as expected, at least as I expected. 

Just to clarify what's the STR you guys did? I used it in this comment; https://bugzilla.mozilla.org/show_bug.cgi?id=1807073#c8

**Comment by jonalmeida** [comment]
> Okay, I did double-check both on Android Emulator and on Pixel 3. This change works as expected, at least as I expected.
> 
> Just to clarify what's the STR you guys did? I used it in this comment; https://bugzilla.mozilla.org/show_bug.cgi?id=1807073#c8

Yes, I can use the same STR and reproduce the bug on the same webpage. In the video, you can see that I have built Fenix with the same patches here (HEAD is at 9a2dfe4a98):

https://github.com/mozilla-mobile/firefox-android/assets/1370580/7a9a6058-7a4c-4fe2-a79b-128847aee52b

**Comment by hiikezoe** [comment]
I am sorry I was on PTO so I hadn't responded. 

Anyways, I am now trying to reproduce the issue, but I haven't been able to do it yet. And now I stated suspecting it's because of debug builds I am using?

I am going to try an opt build.

**Comment by hiikezoe** [comment]
Though with a local opt Gecko build I can't reproduce the issue, I realized the behavior on the recording is slightly different from what I am seeing. It noticed me that this PR has a regression that the dynamic toolbar doesn't move at all while scrolling the contents.  That makes me suspect that `requestDisallowInterceptTouchEvent` also does disallow intercepting touch events in the component for the dynamic toolbar, thus we need an independent API instead of `requestDisallowInterceptTouchEvent`.

**Comment by titooan** [comment]
Hey @hiikezoe, 
We've investigated the bug further and we probably found its cause out. 

There's a draft patch here: #5075, where I still need to update the tests. We basically took your patch and applied some changes. 

We realised that each new motion event actually updates the same object. That's why `updateInputResult` didn't have the expected behavior. 
Then I proposed a very basic way to adapt the behavior of `requestDisallowInterceptTouchEvent` so that it doesn't break the toolbar behavior. 

The code needs some improvments, and as I said I need to update the tests, but I think we're on a good path. What do you think?

**Comment by jonalmeida** [comment]
@hiikezoe we've gone through some iterations from the patch you've provided and we are going to land that in #5075 . Thank you for this work to get us started! 🙏

**Comment by hiikezoe** [comment]
Thank you, Jon and Titouan! Great to hear that!

(I somehow missed the last sentence in [this Tituouan's comment](https://github.com/mozilla-mobile/firefox-android/pull/4870#issuecomment-1881600046) so I didn't response at  all. I am sorry for that)

**Pull request closed without merging**
