### PR TITLE
Bug 1829619 - Fix external ActivityNotFoundException for default browser settings

### PR DESCRIPTION
**Pull request by rahulsainani**
Details in the bug.

### How
– Create `startExternalActivitySafe` extension function that takes in lamda `onActivityNotPresent`.
– Use the above extension function in existing `navigateToDefaultBrowserAppsSettings`
– Extract `openDefaultBrowserSumoPage` as a private extension function for ease of use and re-usability. 

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1829619

### CODE REVIEW

**Review by Amejia481 — COMMENTED** [review]
I noticed with have a similar function on AC, should we have to update it too?
https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Context.kt#L27

**Comment by rahulsainani** [comment]
> I noticed with have a similar function on AC, should we have to update it too? https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Context.kt#L27

Good to know! We should try to commonalize this and try to use the A-C one going forward.

**Comment by rahulsainani** [comment]
@Amejia481 Thanks for the review! 

As discussed, removing the `HomeDeepLinkIntentProcessorTest.make_default_browser deep_link for above API 23` test as it is tricky to mock `ResolveInfo` for `PackageManager` and this PR is fixing a crash that's important. 

Adding my thoughts here: the test was testing the implementation, verifying the calling of `startActivity`. If the implementation changes, which it did, but the output didn't, the test failed. Which brings attention to whether we were testing the right thing? Should we test the implementation or test the output result?

**Comment by Amejia481** [comment]
> @Amejia481 Thanks for the review!
> 
> As discussed, removing the `HomeDeepLinkIntentProcessorTest.make_default_browser deep_link for above API 23` test as it is tricky to mock `ResolveInfo` for `PackageManager` and this PR is fixing a crash that's important.
> 
> Adding my thoughts here: the test was testing the implementation, verifying the calling of `startActivity`. If the implementation changes, which it did, but the output didn't, the test failed. Which brings attention to whether we were testing the right thing? Should we test the implementation or test the output result?
> 
> Added the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1829793) for tracking.

Yeah, I think the main goal with our tests is to have a safety net that alert us when when something is broken, ideally we should test the expected behaviour, but if it's near to impossible or super hard to do so, I prefer that we have tests that verify the implementation (Implicitly check the expected behaviour) than no having no tests no safety net.

**Comment by rahulsainani** [comment]
@Mergifyio backport releases_v113

**Pull request merged**
