### PR TITLE
Bug 1812196 - Sets height of `Learn more about Sync` in Logins and passwords- Saved logins

### PR DESCRIPTION
**Pull request by gitstart**
The PR increases the clickable area of the `Learn more about Sync` in the Logins and passwords- Saved logins page

### Screenshots
| Issue | Fix |
| ----- | --- |
| FNXOSS-58 | [FNXOSS-56 FIX.webm](https://user-images.githubusercontent.com/2725300/216570647-86dac6d5-d6f0-4c04-9af3-f61e832b9252.webm) |

### Pull Request checklist
 - [ ] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [ ] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1812196

### CODE REVIEW

**Review by Mugurell — CHANGES_REQUESTED** [review]
Thank you for helping with this!

The same as on https://github.com/mozilla-mobile/firefox-android/pull/883#pullrequestreview-1305172736 though if the issue only affects accessibility then we should directly address that and not change the UI. Left a comment with the approach we usually use fro this.

Also to note that based on the ticket there should'nt be any a11y suggestions but in your video it seems like there is one other View we need to update. Do you plan to update it in this PR also?

**Comment by gitstart** [comment]
Thank you @Mugurell for reviewing🙏.
Will soon push the requested changes. 🚀

**Comment by gitstart** [comment]
Hello @Mugurell,
Requested changes are pushed. 🚀

**Comment by gitstart** [comment]
The remaining accessibility issue is a `Text scaling` issue which will require changing the toolbar UI.

**Comment by Mugurell** [comment]
`test-apk-fenix-debug` failed because of 
> Could not download gradle-python-envs-0.0.26.jar (gradle.plugin.com.jetbrains.python:gradle-python-envs:0.0.26)
Closing and reopening the PR to restart CI tasks.

**Comment by Mugurell** [comment]
bors try

**Comment by Mugurell** [comment]
`build-components-feature-search` failed because of https://bugzilla.mozilla.org/show_bug.cgi?id=1803063

`mozilla.components.support.test.robolectric.ExtensionsTest#getProvidedAppContext`failed because of 
> ERROR: Failed to fetch maven artifact org.robolectric:android-all-instrumented:9-robolectric-4913185-2-i4

Lint also failed because of
> 4T08:38:08.348Z] e: /builds/worker/checkouts/vcs/fenix/app/build/generated/source/nimbus/fenixDebug/kotlin/FxNimbus.kt: (11, 48): Unresolved reference: FeatureManifestInterface
[task 2023-02-24T08:38:08.348Z] e: /builds/worker/checkouts/vcs/fenix/app/build/generated/source/nimbus/fenixDebug/kotlin/FxNimbus.kt: (36, 19): Unresolved reference: FeatureManifestInterface
[task 2023-02-24T08:38:08.348Z] e: /builds/worker/checkouts/vcs/fenix/app/build/generated/source/nimbus/fenixDebug/kotlin/FxNimbus.kt: (155, 12): 'initialize' overrides nothing
[task 2023-02-24T08:38:08.348Z] e: /builds/worker/checkouts/vcs/fenix/app/build/generated/source/nimbus/fenixDebug/kotlin/FxNimbus.kt: (194, 12): 'invalidateCachedValues' overrides nothing
[task 2023-02-24T08:38:08.348Z] e: /builds/worker/checkouts/vcs/fenix/app/build/generated/source/nimbus/fenixDebug/kotlin/FxNimbus.kt: (213, 5): 'features' overrides nothing

Trying again.

**Comment by Mugurell** [comment]
bors try

**Review by Mugurell — APPROVED** [review]

**Comment by Mugurell** [comment]
Still seeing `FxNimbus` errors, eg - https://github.com/mozilla-mobile/firefox-android/pull/909/checks?check_run_id=11570898342 which will block landing.

@gitstart Can you please rebase locally on top of the current `main` and also squash your commits to remain with only one before trying to land?

**Comment by gitstart** [comment]
> Still seeing `FxNimbus` errors, eg - https://github.com/mozilla-mobile/firefox-android/pull/909/checks?check_run_id=11570898342 which will block landing.
> 
> @gitstart Can you please rebase locally on top of the current `main` and also squash your commits to remain with only one before trying to land?

Hello @Mugurell,
Rebased with main. All Checks passed.✔
Thank you.🎉

**Comment by Mugurell** [comment]
bors try

**Comment by Mugurell** [comment]
bors ping

**Comment by Mugurell** [comment]
bors try

**Pull request merged**
