### PR TITLE
Bug 1850006 -  Make conservative mode non-default

### PR DESCRIPTION
**Pull request by jackyzy823**
"Conservative" causes a lot of network problems (like download files, add custom search engine) , so let "Conservative" mode only apply on mozilla's services.

Replace by searching " Request(" and deciding the function is only used by Mozilla or public used.

-----------
Not sure how to make a more proper test . ( not sure how to mock a tls 1.3 only httpserver)

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1850006

### CODE REVIEW

**Comment by dcousens** [comment]
Tested on an `arm64-v8a` device, this resolved my TLS 1.3 issues when saving images with a long press.

(Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1849684)

**Comment by jackyzy823** [comment]
Just a note: changing the signature of `Request` will cause the same problem as https://github.com/mozilla-mobile/firefox-android/pull/2535 : https://bugzilla.mozilla.org/show_bug.cgi?id=1860725

**Comment by dcousens** [comment]
@jonalmeida anything that needs to happen for this to merge?

**Comment by jackyzy823** [comment]
Note:
[android-components/components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoader.kt](https://github.com/mozilla-mobile/firefox-android/blob/946b14c07ca9096b56e7ce45829be6fca57599a1/android-components/components/support/images/src/main/java/mozilla/components/support/images/compose/loader/ImageLoader.kt#L149) use conservative=true because it is only used in [fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt](https://github.com/mozilla-mobile/firefox-android/blob/946b14c07ca9096b56e7ce45829be6fca57599a1/fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt#L109)

**Comment by dcousens** [comment]
Thanks for keeping this pull request up to date @jackyzy823, LMK if you need any testing

**Review by jonalmeida — APPROVED** [review]
Thanks for keeping the existing functionality for all the other features, this makes the patch easy to land. I've filed BZ-1876142 as a follow-up so we can wait for this to bake in nightly and then look at removing conservative mode across these features that may not require it.

**Comment by jonalmeida** [comment]
I should have also added a commit to update the changelog since we are changing behaviour here, but I will add this myself to a follow-up PR.

**Comment by jonalmeida** [comment]
A full CI run with UI tests happened in the #5263 PR: https://firefox-ci-tc.services.mozilla.com/tasks/groups/ZT07dwKjR5y0NNvop4C6cQ

**Comment by dcousens** [comment]
Thanks for your work @jackyzy823 and @jonalmeida :blue_heart:

**Pull request merged**
