### PR TITLE
Bug 1807536 - When user presses "Stay in private browsing" button from "Cancel private download" popup the tab should remain open.

### PR DESCRIPTION
**Pull request by iorgamgabriel**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1807536

### CODE REVIEW

**Comment by iorgamgabriel** [comment]
Uploading screen-20230920-155323.mp4…

**Comment by iorgamgabriel** [comment]
https://github.com/mozilla-mobile/firefox-android/assets/8118371/8f694578-6b0c-4439-9a9b-516023c7af99

**Comment by iorgamgabriel** [comment]
https://github.com/mozilla-mobile/firefox-android/assets/8118371/99bfa57b-d5e1-41dd-8adb-ed919cb11e28

**Comment by iorgamgabriel** [comment]
It also contains a fix for this bug. https://bugzilla.mozilla.org/show_bug.cgi?id=1854590

**Comment by gabrielluong** [comment]
We have moved our firefox-android repo over to [mozilla-central](https://hg.mozilla.org/mozilla-central). Please feel free to reopen a new PR against the new repo. You will have to clone the new repository and reapply your changes. Thank you again, and sorry for the inconvenience.

For more information, please see https://github.com/mozilla-mobile/firefox-android/wiki#upcoming-migration-to-mozilla-central.

**Pull request closed without merging**
