### PR TITLE
Bug 1819225 - fix comparator issue with update-experiments output

### PR DESCRIPTION
**Pull request by jeddai**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1819225

### CODE REVIEW

**Comment by jeddai** [comment]
@jonalmeida @Amejia481 I don't have a bug for this – is there a specific way I should put this into a Bugzilla ticket other than selecting `General` as the component and `unspecified` for the version?

**Review by tarikeshaq — APPROVED** [review]
Rubber stamp but makes sense to me!

**Comment by jonalmeida** [comment]
> I don't have a bug for this – is there a specific way I should put this into a Bugzilla ticket other than selecting `General` as the component and `unspecified` for the version?

The Experimentation & Telemetry component would be good: https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix&component=Experimentation%20and%20Telemetry

**Comment by jeddai** [comment]
> The Experimentation & Telemetry component would be good: https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix&component=Experimentation%20and%20Telemetry

Thanks!!

**Pull request merged**
