### PR TITLE
Bug 1810631 - Display name instead of e-mail in menu

### PR DESCRIPTION
**Pull request by gitstart**
### What
Display name instead of e-mail in menu

### Screenshots
| Issue | Fix |
| ----- | --- |
| Screenshot_20230217-105928 |  Screenshot_20230219-081141 |

### Pull Request checklist
 - [x] Quality: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
 - [x] Tests: This PR includes thorough tests or an explanation of why it does not
 - [ ] Changelog: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
 - [ ] Accessibility: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features
### After merge
- Milestone: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- Breaking Changes: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation
https://bugzilla.mozilla.org/show_bug.cgi?id=1810631

### CODE REVIEW

**Review by Mugurell — COMMENTED** [review]
Thank you for your contribution!

This feature is common on multiple platforms where the email is displayed.
A bigger sync is needed with UX and product to confirm if this change is wanted on all platforms / just on Fenix / not at all. Will keep you posted with the discussions result.

**Comment by lime124** [comment]
Agreed - we need to consider the change across our whole ecosystem. I've asked our content team to take this into consideration. Thanks!

**Comment by ewachowiak** [comment]
Looks like the Display Name shows on iOS and nowhere else, but Vesta confirmed that it should be on the backlog to make this change on Android & Desktop. I think it is okay to proceed with this pull request & use Display Name when it is available. When Display Name is not available, account email should show (as it does today).

**Review by Mugurell — CHANGES_REQUESTED** [review]
Looks like this change is approved by UX with just one other detail needed: To fallback on the `email` if the `displayName` is not available.
Would be great if this could be covered by a unit test also, let me know if you need help with this.

**Comment by Mugurell** [comment]
bors try

**Comment by Mugurell** [comment]
@Mergifyio backport releases_v111

**Pull request merged**
